/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ActivateDraftSubscriptionRequest = {
  /**
   * start_date is the new start date for the subscription when activating
   */
  startDate: Date;
};

/** @internal */
export type ActivateDraftSubscriptionRequest$Outbound = {
  start_date: string;
};

/** @internal */
export const ActivateDraftSubscriptionRequest$outboundSchema: z.ZodType<
  ActivateDraftSubscriptionRequest$Outbound,
  z.ZodTypeDef,
  ActivateDraftSubscriptionRequest
> = z.object({
  startDate: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    startDate: "start_date",
  });
});

export function activateDraftSubscriptionRequestToJSON(
  activateDraftSubscriptionRequest: ActivateDraftSubscriptionRequest,
): string {
  return JSON.stringify(
    ActivateDraftSubscriptionRequest$outboundSchema.parse(
      activateDraftSubscriptionRequest,
    ),
  );
}
