/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AddAddonRef,
  AddAddonRef$Outbound,
  AddAddonRef$outboundSchema,
} from "./add-addon-ref.js";
import {
  RemoveAddonRef,
  RemoveAddonRef$Outbound,
  RemoveAddonRef$outboundSchema,
} from "./remove-addon-ref.js";

export type AddAddonParams = {
  addons?: Array<AddAddonRef> | undefined;
  removes?: Array<RemoveAddonRef> | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export type AddAddonParams$Outbound = {
  addons?: Array<AddAddonRef$Outbound> | undefined;
  removes?: Array<RemoveAddonRef$Outbound> | undefined;
  subscription_id?: string | undefined;
};

/** @internal */
export const AddAddonParams$outboundSchema: z.ZodMiniType<
  AddAddonParams$Outbound,
  AddAddonParams
> = z.pipe(
  z.object({
    addons: z.optional(z.array(AddAddonRef$outboundSchema)),
    removes: z.optional(z.array(RemoveAddonRef$outboundSchema)),
    subscriptionId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      subscriptionId: "subscription_id",
    });
  }),
);

export function addAddonParamsToJSON(addAddonParams: AddAddonParams): string {
  return JSON.stringify(AddAddonParams$outboundSchema.parse(addAddonParams));
}
