/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type AddLineItemRequest = {
  amount: string;
  description?: string | undefined;
  displayName: string;
  periodEnd?: Date | undefined;
  periodStart?: Date | undefined;
  quantity: string;
};

/** @internal */
export type AddLineItemRequest$Outbound = {
  amount: string;
  description?: string | undefined;
  display_name: string;
  period_end?: string | undefined;
  period_start?: string | undefined;
  quantity: string;
};

/** @internal */
export const AddLineItemRequest$outboundSchema: z.ZodMiniType<
  AddLineItemRequest$Outbound,
  AddLineItemRequest
> = z.pipe(
  z.object({
    amount: z.string(),
    description: z.optional(z.string()),
    displayName: z.string(),
    periodEnd: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    periodStart: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
    quantity: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      displayName: "display_name",
      periodEnd: "period_end",
      periodStart: "period_start",
    });
  }),
);

export function addLineItemRequestToJSON(
  addLineItemRequest: AddLineItemRequest,
): string {
  return JSON.stringify(
    AddLineItemRequest$outboundSchema.parse(addLineItemRequest),
  );
}
