/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  AddAddonRef,
  AddAddonRef$inboundSchema,
  AddAddonRef$Outbound,
  AddAddonRef$outboundSchema,
} from "./add-addon-ref.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type AddAddonParams = {
  addons?: Array<AddAddonRef> | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const AddAddonParams$inboundSchema: z.ZodMiniType<
  AddAddonParams,
  unknown
> = z.pipe(
  z.object({
    addons: types.optional(z.array(AddAddonRef$inboundSchema)),
    subscription_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "subscription_id": "subscriptionId",
    });
  }),
);
/** @internal */
export type AddAddonParams$Outbound = {
  addons?: Array<AddAddonRef$Outbound> | undefined;
  subscription_id?: string | undefined;
};

/** @internal */
export const AddAddonParams$outboundSchema: z.ZodMiniType<
  AddAddonParams$Outbound,
  AddAddonParams
> = z.pipe(
  z.object({
    addons: z.optional(z.array(AddAddonRef$outboundSchema)),
    subscriptionId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      subscriptionId: "subscription_id",
    });
  }),
);

export function addAddonParamsToJSON(addAddonParams: AddAddonParams): string {
  return JSON.stringify(AddAddonParams$outboundSchema.parse(addAddonParams));
}
export function addAddonParamsFromJSON(
  jsonString: string,
): SafeParseResult<AddAddonParams, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddAddonParams$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddAddonParams' from JSON`,
  );
}
