/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const AddonAssociationEntityType = {
  Subscription: "subscription",
  Plan: "plan",
  Addon: "addon",
} as const;
export type AddonAssociationEntityType = OpenEnum<
  typeof AddonAssociationEntityType
>;

/** @internal */
export const AddonAssociationEntityType$inboundSchema: z.ZodType<
  AddonAssociationEntityType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(AddonAssociationEntityType);
