/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const AggregationType = {
  Count: "COUNT",
  Sum: "SUM",
  Avg: "AVG",
  CountUnique: "COUNT_UNIQUE",
  Latest: "LATEST",
  SumWithMultiplier: "SUM_WITH_MULTIPLIER",
  Max: "MAX",
  WeightedSum: "WEIGHTED_SUM",
} as const;
export type AggregationType = OpenEnum<typeof AggregationType>;

/** @internal */
export const AggregationType$inboundSchema: z.ZodMiniType<
  AggregationType,
  unknown
> = openEnums.inboundSchema(AggregationType);
/** @internal */
export const AggregationType$outboundSchema: z.ZodMiniType<
  string,
  AggregationType
> = openEnums.outboundSchema(AggregationType);
