/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const AlertCondition = {
  Above: "above",
  Below: "below",
} as const;
export type AlertCondition = OpenEnum<typeof AlertCondition>;

/** @internal */
export const AlertCondition$inboundSchema: z.ZodMiniType<
  AlertCondition,
  unknown
> = openEnums.inboundSchema(AlertCondition);
/** @internal */
export const AlertCondition$outboundSchema: z.ZodMiniType<
  string,
  AlertCondition
> = openEnums.outboundSchema(AlertCondition);
