/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  AlertCondition,
  AlertCondition$inboundSchema,
  AlertCondition$outboundSchema,
} from "./alertcondition.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type AlertThreshold = {
  condition?: AlertCondition | undefined;
  threshold?: number | undefined;
};

/** @internal */
export const AlertThreshold$inboundSchema: z.ZodType<
  AlertThreshold,
  z.ZodTypeDef,
  unknown
> = z.object({
  condition: types.optional(AlertCondition$inboundSchema),
  threshold: types.optional(types.number()),
});
/** @internal */
export type AlertThreshold$Outbound = {
  condition?: string | undefined;
  threshold?: number | undefined;
};

/** @internal */
export const AlertThreshold$outboundSchema: z.ZodType<
  AlertThreshold$Outbound,
  z.ZodTypeDef,
  AlertThreshold
> = z.object({
  condition: AlertCondition$outboundSchema.optional(),
  threshold: z.number().optional(),
});

export function alertThresholdToJSON(alertThreshold: AlertThreshold): string {
  return JSON.stringify(AlertThreshold$outboundSchema.parse(alertThreshold));
}
export function alertThresholdFromJSON(
  jsonString: string,
): SafeParseResult<AlertThreshold, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AlertThreshold$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AlertThreshold' from JSON`,
  );
}
