/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const AlertEntityType = {
  Wallet: "wallet",
  Feature: "feature",
} as const;
export type AlertEntityType = OpenEnum<typeof AlertEntityType>;

/** @internal */
export const AlertEntityType$inboundSchema: z.ZodMiniType<
  AlertEntityType,
  unknown
> = openEnums.inboundSchema(AlertEntityType);
/** @internal */
export const AlertEntityType$outboundSchema: z.ZodMiniType<
  string,
  AlertEntityType
> = openEnums.outboundSchema(AlertEntityType);
