/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SortDirection,
  SortDirection$inboundSchema,
  SortDirection$outboundSchema,
} from "./sort-direction.js";

export type AnalyticsSortSpec = {
  dir?: SortDirection | undefined;
  field?: string | undefined;
};

/** @internal */
export const AnalyticsSortSpec$inboundSchema: z.ZodMiniType<
  AnalyticsSortSpec,
  unknown
> = z.object({
  dir: types.optional(SortDirection$inboundSchema),
  field: types.optional(types.string()),
});
/** @internal */
export type AnalyticsSortSpec$Outbound = {
  dir?: string | undefined;
  field?: string | undefined;
};

/** @internal */
export const AnalyticsSortSpec$outboundSchema: z.ZodMiniType<
  AnalyticsSortSpec$Outbound,
  AnalyticsSortSpec
> = z.object({
  dir: z.optional(SortDirection$outboundSchema),
  field: z.optional(z.string()),
});

export function analyticsSortSpecToJSON(
  analyticsSortSpec: AnalyticsSortSpec,
): string {
  return JSON.stringify(
    AnalyticsSortSpec$outboundSchema.parse(analyticsSortSpec),
  );
}
export function analyticsSortSpecFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsSortSpec, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsSortSpec$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsSortSpec' from JSON`,
  );
}
