/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  AnalyticsViewDefinition,
  AnalyticsViewDefinition$Outbound,
  AnalyticsViewDefinition$outboundSchema,
} from "./analytics-view-definition.js";

export type AnalyticsQueryRequest = {
  definition: AnalyticsViewDefinition;
  variables?: { [k: string]: Array<string> } | undefined;
};

/** @internal */
export type AnalyticsQueryRequest$Outbound = {
  definition: AnalyticsViewDefinition$Outbound;
  variables?: { [k: string]: Array<string> } | undefined;
};

/** @internal */
export const AnalyticsQueryRequest$outboundSchema: z.ZodMiniType<
  AnalyticsQueryRequest$Outbound,
  AnalyticsQueryRequest
> = z.object({
  definition: AnalyticsViewDefinition$outboundSchema,
  variables: z.optional(z.record(z.string(), z.array(z.string()))),
});

export function analyticsQueryRequestToJSON(
  analyticsQueryRequest: AnalyticsQueryRequest,
): string {
  return JSON.stringify(
    AnalyticsQueryRequest$outboundSchema.parse(analyticsQueryRequest),
  );
}
