/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const BillingCycle = {
  Anniversary: "anniversary",
  Calendar: "calendar",
} as const;
export type BillingCycle = OpenEnum<typeof BillingCycle>;

/** @internal */
export const BillingCycle$inboundSchema: z.ZodMiniType<BillingCycle, unknown> =
  openEnums.inboundSchema(BillingCycle);
/** @internal */
export const BillingCycle$outboundSchema: z.ZodMiniType<string, BillingCycle> =
  openEnums.outboundSchema(BillingCycle);
