/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const BillingPeriodBehaviour = {
  Unchanged: "unchanged",
  AnchorAtEffect: "anchor_at_effect",
  AnchorAtConfig: "anchor_at_config",
} as const;
export type BillingPeriodBehaviour = OpenEnum<typeof BillingPeriodBehaviour>;

/** @internal */
export const BillingPeriodBehaviour$inboundSchema: z.ZodMiniType<
  BillingPeriodBehaviour,
  unknown
> = openEnums.inboundSchema(BillingPeriodBehaviour);
/** @internal */
export const BillingPeriodBehaviour$outboundSchema: z.ZodMiniType<
  string,
  BillingPeriodBehaviour
> = openEnums.outboundSchema(BillingPeriodBehaviour);
