/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * created | updated
 */
export const ChangedSubscriptionAction = {
  Created: "created",
  Updated: "updated",
} as const;
/**
 * created | updated
 */
export type ChangedSubscriptionAction = OpenEnum<
  typeof ChangedSubscriptionAction
>;

/** @internal */
export const ChangedSubscriptionAction$inboundSchema: z.ZodMiniType<
  ChangedSubscriptionAction,
  unknown
> = openEnums.inboundSchema(ChangedSubscriptionAction);
