/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  ChangedSubscriptionAction,
  ChangedSubscriptionAction$inboundSchema,
} from "./changed-subscription-action.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$inboundSchema,
} from "./subscription-status.js";

export type ChangedSubscription = {
  /**
   * created | updated
   */
  action?: ChangedSubscriptionAction | undefined;
  currentPeriodEnd?: Date | undefined;
  id?: string | undefined;
  status?: SubscriptionStatus | undefined;
  trialEnd?: Date | undefined;
};

/** @internal */
export const ChangedSubscription$inboundSchema: z.ZodMiniType<
  ChangedSubscription,
  unknown
> = z.pipe(
  z.object({
    action: types.optional(ChangedSubscriptionAction$inboundSchema),
    current_period_end: types.optional(types.date()),
    id: types.optional(types.string()),
    status: types.optional(SubscriptionStatus$inboundSchema),
    trial_end: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "current_period_end": "currentPeriodEnd",
      "trial_end": "trialEnd",
    });
  }),
);

export function changedSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<ChangedSubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChangedSubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChangedSubscription' from JSON`,
  );
}
