/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * created (proration invoice) | wallet_credit (downgrade credit)
 */
export const ChangedInvoiceAction = {
  Created: "created",
  WalletCredit: "wallet_credit",
} as const;
/**
 * created (proration invoice) | wallet_credit (downgrade credit)
 */
export type ChangedInvoiceAction = OpenEnum<typeof ChangedInvoiceAction>;

/** @internal */
export const ChangedInvoiceAction$inboundSchema: z.ZodMiniType<
  ChangedInvoiceAction,
  unknown
> = openEnums.inboundSchema(ChangedInvoiceAction);
