/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  CreateSubscriptionParams,
  CreateSubscriptionParams$inboundSchema,
} from "./create-subscription-params.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type CheckoutJSONBCheckoutConfiguration = {
  createSubscriptionParams?: CreateSubscriptionParams | undefined;
};

/** @internal */
export const CheckoutJSONBCheckoutConfiguration$inboundSchema: z.ZodMiniType<
  CheckoutJSONBCheckoutConfiguration,
  unknown
> = z.pipe(
  z.object({
    create_subscription_params: types.optional(
      CreateSubscriptionParams$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "create_subscription_params": "createSubscriptionParams",
    });
  }),
);

export function checkoutJSONBCheckoutConfigurationFromJSON(
  jsonString: string,
): SafeParseResult<CheckoutJSONBCheckoutConfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CheckoutJSONBCheckoutConfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckoutJSONBCheckoutConfiguration' from JSON`,
  );
}
