/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CheckoutAction = {
  CreateSubscription: "create_subscription",
} as const;
export type CheckoutAction = ClosedEnum<typeof CheckoutAction>;

/** @internal */
export const CheckoutAction$inboundSchema: z.ZodMiniEnum<
  typeof CheckoutAction
> = z.enum(CheckoutAction);
/** @internal */
export const CheckoutAction$outboundSchema: z.ZodMiniEnum<
  typeof CheckoutAction
> = CheckoutAction$inboundSchema;
