/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CloneFeatureRequest = {
  /**
   * Description overrides the source feature's description when provided
   */
  description?: string | undefined;
  /**
   * LookupKey is required and must be unique across published features
   */
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  /**
   * Name is required and must be different from the source feature's name
   */
  name?: string | undefined;
};

/** @internal */
export type CloneFeatureRequest$Outbound = {
  description?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export const CloneFeatureRequest$outboundSchema: z.ZodMiniType<
  CloneFeatureRequest$Outbound,
  CloneFeatureRequest
> = z.pipe(
  z.object({
    description: z.optional(z.string()),
    lookupKey: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.string())),
    name: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      lookupKey: "lookup_key",
    });
  }),
);

export function cloneFeatureRequestToJSON(
  cloneFeatureRequest: CloneFeatureRequest,
): string {
  return JSON.stringify(
    CloneFeatureRequest$outboundSchema.parse(cloneFeatureRequest),
  );
}
