/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CloneFeatureRequest,
  CloneFeatureRequest$Outbound,
  CloneFeatureRequest$outboundSchema,
} from "./clonefeaturerequest.js";

export type CloneFeatureRequestRequest = {
  /**
   * Source Feature ID
   */
  id: string;
  /**
   * Clone configuration
   */
  body: CloneFeatureRequest;
};

/** @internal */
export type CloneFeatureRequestRequest$Outbound = {
  id: string;
  body: CloneFeatureRequest$Outbound;
};

/** @internal */
export const CloneFeatureRequestRequest$outboundSchema: z.ZodType<
  CloneFeatureRequestRequest$Outbound,
  z.ZodTypeDef,
  CloneFeatureRequestRequest
> = z.object({
  id: z.string(),
  body: CloneFeatureRequest$outboundSchema,
});

export function cloneFeatureRequestRequestToJSON(
  cloneFeatureRequestRequest: CloneFeatureRequestRequest,
): string {
  return JSON.stringify(
    CloneFeatureRequestRequest$outboundSchema.parse(cloneFeatureRequestRequest),
  );
}
