/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type CloneFeatureRequest = {
  /**
   * Description overrides the source feature's description when provided
   */
  description?: string | undefined;
  /**
   * LookupKey is required and must be unique across published features
   */
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  /**
   * Name is required and must be different from the source feature's name
   */
  name?: string | undefined;
};

/** @internal */
export type CloneFeatureRequest$Outbound = {
  description?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export const CloneFeatureRequest$outboundSchema: z.ZodType<
  CloneFeatureRequest$Outbound,
  z.ZodTypeDef,
  CloneFeatureRequest
> = z.object({
  description: z.string().optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    lookupKey: "lookup_key",
  });
});

export function cloneFeatureRequestToJSON(
  cloneFeatureRequest: CloneFeatureRequest,
): string {
  return JSON.stringify(
    CloneFeatureRequest$outboundSchema.parse(cloneFeatureRequest),
  );
}
