/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ColumnRole = {
  Dimension: "dimension",
  Metric: "metric",
} as const;
export type ColumnRole = OpenEnum<typeof ColumnRole>;

/** @internal */
export const ColumnRole$inboundSchema: z.ZodMiniType<ColumnRole, unknown> =
  openEnums.inboundSchema(ColumnRole);
