/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const CouponType = {
  Fixed: "fixed",
  Percentage: "percentage",
} as const;
export type CouponType = OpenEnum<typeof CouponType>;

/** @internal */
export const CouponType$inboundSchema: z.ZodType<
  CouponType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CouponType);
/** @internal */
export const CouponType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  CouponType
> = openEnums.outboundSchema(CouponType);
