/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const CouponType = {
  Fixed: "fixed",
  Percentage: "percentage",
} as const;
export type CouponType = OpenEnum<typeof CouponType>;

/** @internal */
export const CouponType$inboundSchema: z.ZodMiniType<CouponType, unknown> =
  openEnums.inboundSchema(CouponType);
/** @internal */
export const CouponType$outboundSchema: z.ZodMiniType<string, CouponType> =
  openEnums.outboundSchema(CouponType);
