/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  S3JobConfig,
  S3JobConfig$Outbound,
  S3JobConfig$outboundSchema,
} from "./s3-job-config.js";
import {
  ScheduledTaskEntityType,
  ScheduledTaskEntityType$outboundSchema,
} from "./scheduled-task-entity-type.js";
import {
  ScheduledTaskInterval,
  ScheduledTaskInterval$outboundSchema,
} from "./scheduled-task-interval.js";

export type CreateScheduledTaskRequest = {
  connectionId: string;
  enabled?: boolean | undefined;
  entityType: ScheduledTaskEntityType;
  interval: ScheduledTaskInterval;
  jobConfig: S3JobConfig;
};

/** @internal */
export type CreateScheduledTaskRequest$Outbound = {
  connection_id: string;
  enabled?: boolean | undefined;
  entity_type: string;
  interval: string;
  job_config: S3JobConfig$Outbound;
};

/** @internal */
export const CreateScheduledTaskRequest$outboundSchema: z.ZodMiniType<
  CreateScheduledTaskRequest$Outbound,
  CreateScheduledTaskRequest
> = z.pipe(
  z.object({
    connectionId: z.string(),
    enabled: z.optional(z.boolean()),
    entityType: ScheduledTaskEntityType$outboundSchema,
    interval: ScheduledTaskInterval$outboundSchema,
    jobConfig: S3JobConfig$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      connectionId: "connection_id",
      entityType: "entity_type",
      jobConfig: "job_config",
    });
  }),
);

export function createScheduledTaskRequestToJSON(
  createScheduledTaskRequest: CreateScheduledTaskRequest,
): string {
  return JSON.stringify(
    CreateScheduledTaskRequest$outboundSchema.parse(createScheduledTaskRequest),
  );
}
