/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  CreatePriceRequest,
  CreatePriceRequest$Outbound,
  CreatePriceRequest$outboundSchema,
} from "./createpricerequest.js";

export type CreateBulkPriceRequest = {
  items: Array<CreatePriceRequest>;
};

/** @internal */
export type CreateBulkPriceRequest$Outbound = {
  items: Array<CreatePriceRequest$Outbound>;
};

/** @internal */
export const CreateBulkPriceRequest$outboundSchema: z.ZodType<
  CreateBulkPriceRequest$Outbound,
  z.ZodTypeDef,
  CreateBulkPriceRequest
> = z.object({
  items: z.array(CreatePriceRequest$outboundSchema),
});

export function createBulkPriceRequestToJSON(
  createBulkPriceRequest: CreateBulkPriceRequest,
): string {
  return JSON.stringify(
    CreateBulkPriceRequest$outboundSchema.parse(createBulkPriceRequest),
  );
}
