/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AlertSettings,
  AlertSettings$Outbound,
  AlertSettings$outboundSchema,
} from "./alertsettings.js";
import {
  CreateMeterRequest,
  CreateMeterRequest$Outbound,
  CreateMeterRequest$outboundSchema,
} from "./createmeterrequest.js";
import { FeatureType, FeatureType$outboundSchema } from "./featuretype.js";
import {
  ReportingUnit,
  ReportingUnit$Outbound,
  ReportingUnit$outboundSchema,
} from "./reportingunit.js";

export type CreateFeatureRequest = {
  alertSettings?: AlertSettings | undefined;
  description?: string | undefined;
  /**
   * GroupID is the id of the group to add the feature to
   */
  groupId?: string | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: CreateMeterRequest | undefined;
  meterId?: string | undefined;
  name: string;
  reportingUnit?: ReportingUnit | undefined;
  type: FeatureType;
  unitPlural?: string | undefined;
  unitSingular?: string | undefined;
};

/** @internal */
export type CreateFeatureRequest$Outbound = {
  alert_settings?: AlertSettings$Outbound | undefined;
  description?: string | undefined;
  group_id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: CreateMeterRequest$Outbound | undefined;
  meter_id?: string | undefined;
  name: string;
  reporting_unit?: ReportingUnit$Outbound | undefined;
  type: string;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

/** @internal */
export const CreateFeatureRequest$outboundSchema: z.ZodType<
  CreateFeatureRequest$Outbound,
  z.ZodTypeDef,
  CreateFeatureRequest
> = z.object({
  alertSettings: AlertSettings$outboundSchema.optional(),
  description: z.string().optional(),
  groupId: z.string().optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  meter: CreateMeterRequest$outboundSchema.optional(),
  meterId: z.string().optional(),
  name: z.string(),
  reportingUnit: ReportingUnit$outboundSchema.optional(),
  type: FeatureType$outboundSchema,
  unitPlural: z.string().optional(),
  unitSingular: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    alertSettings: "alert_settings",
    groupId: "group_id",
    lookupKey: "lookup_key",
    meterId: "meter_id",
    reportingUnit: "reporting_unit",
    unitPlural: "unit_plural",
    unitSingular: "unit_singular",
  });
});

export function createFeatureRequestToJSON(
  createFeatureRequest: CreateFeatureRequest,
): string {
  return JSON.stringify(
    CreateFeatureRequest$outboundSchema.parse(createFeatureRequest),
  );
}
