/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CreateInvoiceLineItemRequest,
  CreateInvoiceLineItemRequest$Outbound,
  CreateInvoiceLineItemRequest$outboundSchema,
} from "./createinvoicelineitemrequest.js";
import {
  InvoiceBillingReason,
  InvoiceBillingReason$outboundSchema,
} from "./invoicebillingreason.js";
import {
  InvoiceCoupon,
  InvoiceCoupon$Outbound,
  InvoiceCoupon$outboundSchema,
} from "./invoicecoupon.js";
import {
  InvoiceLineItemCoupon,
  InvoiceLineItemCoupon$Outbound,
  InvoiceLineItemCoupon$outboundSchema,
} from "./invoicelineitemcoupon.js";
import {
  InvoiceStatus,
  InvoiceStatus$outboundSchema,
} from "./invoicestatus.js";
import { InvoiceType, InvoiceType$outboundSchema } from "./invoicetype.js";
import {
  PaymentStatus,
  PaymentStatus$outboundSchema,
} from "./paymentstatus.js";
import {
  TaxRateOverride,
  TaxRateOverride$Outbound,
  TaxRateOverride$outboundSchema,
} from "./taxrateoverride.js";
import {
  TaxRateResponse,
  TaxRateResponse$Outbound,
  TaxRateResponse$outboundSchema,
} from "./taxrateresponse.js";

export type CreateInvoiceRequest = {
  /**
   * amount_due is the total amount that needs to be paid for this invoice
   */
  amountDue: string;
  /**
   * amount_paid is the amount that has been paid towards this invoice
   */
  amountPaid?: string | undefined;
  /**
   * billing_period is the period this invoice covers (e.g., "monthly", "yearly")
   */
  billingPeriod?: string | undefined;
  billingReason?: InvoiceBillingReason | undefined;
  /**
   * coupons
   */
  coupons?: Array<string> | undefined;
  /**
   * currency is the three-letter ISO currency code (e.g., USD, EUR) for the invoice
   */
  currency: string;
  /**
   * customer_id is the unique identifier of the customer this invoice belongs to
   */
  customerId: string;
  /**
   * description is an optional text description of the invoice
   */
  description?: string | undefined;
  /**
   * due_date is the date by which payment is expected
   */
  dueDate?: Date | undefined;
  /**
   * idempotency_key is an optional key used to prevent duplicate invoice creation
   */
  idempotencyKey?: string | undefined;
  /**
   * Invoice Coupons
   */
  invoiceCoupons?: Array<InvoiceCoupon> | undefined;
  /**
   * invoice_number is an optional human-readable identifier for the invoice
   */
  invoiceNumber?: string | undefined;
  /**
   * invoice_pdf_url is the URL where customers can download the PDF version of this invoice
   */
  invoicePdfUrl?: string | undefined;
  invoiceStatus?: InvoiceStatus | undefined;
  invoiceType?: InvoiceType | undefined;
  /**
   * issue_date overrides the user-facing date of the invoice.
   *
   * @remarks
   * Defaults to created_at if not provided.
   */
  issueDate?: Date | undefined;
  /**
   * Invoice Line Item Coupons
   */
  lineItemCoupons?: Array<InvoiceLineItemCoupon> | undefined;
  /**
   * line_items contains the individual items that make up this invoice
   */
  lineItems?: Array<CreateInvoiceLineItemRequest> | undefined;
  metadata?: { [k: string]: string } | undefined;
  paymentStatus?: PaymentStatus | undefined;
  /**
   * period_end is the end date of the billing period
   */
  periodEnd?: Date | undefined;
  /**
   * period_start is the start date of the billing period
   */
  periodStart?: Date | undefined;
  /**
   * prepared_tax_rates contains the tax rates pre-resolved by the caller (e.g., billing service)
   */
  preparedTaxRates?: Array<TaxRateResponse> | undefined;
  /**
   * subscription_id is the optional unique identifier of the subscription associated with this invoice
   */
  subscriptionId?: string | undefined;
  /**
   * subtotal is the amount before taxes and discounts are applied
   */
  subtotal: string;
  /**
   * tax_rate_overrides is the tax rate overrides to be applied to the invoice
   */
  taxRateOverrides?: Array<TaxRateOverride> | undefined;
  /**
   * tax_rates
   */
  taxRates?: Array<string> | undefined;
  /**
   * total is the total amount of the invoice including taxes and discounts
   */
  total: string;
  /**
   * total_prepaid_applied is the total amount of prepaid applied to this invoice.
   */
  totalPrepaidApplied?: string | undefined;
};

/** @internal */
export type CreateInvoiceRequest$Outbound = {
  amount_due: string;
  amount_paid?: string | undefined;
  billing_period?: string | undefined;
  billing_reason?: string | undefined;
  coupons?: Array<string> | undefined;
  currency: string;
  customer_id: string;
  description?: string | undefined;
  due_date?: string | undefined;
  idempotency_key?: string | undefined;
  invoice_coupons?: Array<InvoiceCoupon$Outbound> | undefined;
  invoice_number?: string | undefined;
  invoice_pdf_url?: string | undefined;
  invoice_status?: string | undefined;
  invoice_type?: string | undefined;
  issue_date?: string | undefined;
  line_item_coupons?: Array<InvoiceLineItemCoupon$Outbound> | undefined;
  line_items?: Array<CreateInvoiceLineItemRequest$Outbound> | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_status?: string | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  prepared_tax_rates?: Array<TaxRateResponse$Outbound> | undefined;
  subscription_id?: string | undefined;
  subtotal: string;
  tax_rate_overrides?: Array<TaxRateOverride$Outbound> | undefined;
  tax_rates?: Array<string> | undefined;
  total: string;
  total_prepaid_applied?: string | undefined;
};

/** @internal */
export const CreateInvoiceRequest$outboundSchema: z.ZodType<
  CreateInvoiceRequest$Outbound,
  z.ZodTypeDef,
  CreateInvoiceRequest
> = z.object({
  amountDue: z.string(),
  amountPaid: z.string().optional(),
  billingPeriod: z.string().optional(),
  billingReason: InvoiceBillingReason$outboundSchema.optional(),
  coupons: z.array(z.string()).optional(),
  currency: z.string(),
  customerId: z.string(),
  description: z.string().optional(),
  dueDate: z.date().transform(v => v.toISOString()).optional(),
  idempotencyKey: z.string().optional(),
  invoiceCoupons: z.array(InvoiceCoupon$outboundSchema).optional(),
  invoiceNumber: z.string().optional(),
  invoicePdfUrl: z.string().optional(),
  invoiceStatus: InvoiceStatus$outboundSchema.optional(),
  invoiceType: InvoiceType$outboundSchema.optional(),
  issueDate: z.date().transform(v => v.toISOString()).optional(),
  lineItemCoupons: z.array(InvoiceLineItemCoupon$outboundSchema).optional(),
  lineItems: z.array(CreateInvoiceLineItemRequest$outboundSchema).optional(),
  metadata: z.record(z.string()).optional(),
  paymentStatus: PaymentStatus$outboundSchema.optional(),
  periodEnd: z.date().transform(v => v.toISOString()).optional(),
  periodStart: z.date().transform(v => v.toISOString()).optional(),
  preparedTaxRates: z.array(TaxRateResponse$outboundSchema).optional(),
  subscriptionId: z.string().optional(),
  subtotal: z.string(),
  taxRateOverrides: z.array(TaxRateOverride$outboundSchema).optional(),
  taxRates: z.array(z.string()).optional(),
  total: z.string(),
  totalPrepaidApplied: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    amountDue: "amount_due",
    amountPaid: "amount_paid",
    billingPeriod: "billing_period",
    billingReason: "billing_reason",
    customerId: "customer_id",
    dueDate: "due_date",
    idempotencyKey: "idempotency_key",
    invoiceCoupons: "invoice_coupons",
    invoiceNumber: "invoice_number",
    invoicePdfUrl: "invoice_pdf_url",
    invoiceStatus: "invoice_status",
    invoiceType: "invoice_type",
    issueDate: "issue_date",
    lineItemCoupons: "line_item_coupons",
    lineItems: "line_items",
    paymentStatus: "payment_status",
    periodEnd: "period_end",
    periodStart: "period_start",
    preparedTaxRates: "prepared_tax_rates",
    subscriptionId: "subscription_id",
    taxRateOverrides: "tax_rate_overrides",
    taxRates: "tax_rates",
    totalPrepaidApplied: "total_prepaid_applied",
  });
});

export function createInvoiceRequestToJSON(
  createInvoiceRequest: CreateInvoiceRequest,
): string {
  return JSON.stringify(
    CreateInvoiceRequest$outboundSchema.parse(createInvoiceRequest),
  );
}
