/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  EntitlementResponse,
  EntitlementResponse$inboundSchema,
} from "./entitlementresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CreateBulkEntitlementResponse = {
  items?: Array<EntitlementResponse> | undefined;
};

/** @internal */
export const CreateBulkEntitlementResponse$inboundSchema: z.ZodType<
  CreateBulkEntitlementResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: types.optional(z.array(EntitlementResponse$inboundSchema)),
});

export function createBulkEntitlementResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBulkEntitlementResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBulkEntitlementResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBulkEntitlementResponse' from JSON`,
  );
}
