/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const CreditGrantApplicationReason = {
  FirstTimeRecurringCreditGrant: "first_time_recurring_credit_grant",
  RecurringCreditGrant: "recurring_credit_grant",
  OnetimeCreditGrant: "onetime_credit_grant",
} as const;
export type CreditGrantApplicationReason = OpenEnum<
  typeof CreditGrantApplicationReason
>;

/** @internal */
export const CreditGrantApplicationReason$inboundSchema: z.ZodMiniType<
  CreditGrantApplicationReason,
  unknown
> = openEnums.inboundSchema(CreditGrantApplicationReason);
