/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  CustomerLookupResult,
  CustomerLookupResult$inboundSchema,
} from "./customerlookupresult.js";
import { FailurePoint, FailurePoint$inboundSchema } from "./failurepoint.js";
import {
  MeterMatchingResult,
  MeterMatchingResult$inboundSchema,
} from "./metermatchingresult.js";
import {
  PriceLookupResult,
  PriceLookupResult$inboundSchema,
} from "./pricelookupresult.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  SubscriptionLineItemLookupResult,
  SubscriptionLineItemLookupResult$inboundSchema,
} from "./subscriptionlineitemlookupresult.js";

export type DebugTracker = {
  customerLookup?: CustomerLookupResult | undefined;
  failurePoint?: FailurePoint | undefined;
  meterMatching?: MeterMatchingResult | undefined;
  priceLookup?: PriceLookupResult | undefined;
  subscriptionLineItemLookup?: SubscriptionLineItemLookupResult | undefined;
};

/** @internal */
export const DebugTracker$inboundSchema: z.ZodType<
  DebugTracker,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_lookup: types.optional(CustomerLookupResult$inboundSchema),
  failure_point: types.optional(FailurePoint$inboundSchema),
  meter_matching: types.optional(MeterMatchingResult$inboundSchema),
  price_lookup: types.optional(PriceLookupResult$inboundSchema),
  subscription_line_item_lookup: types.optional(
    SubscriptionLineItemLookupResult$inboundSchema,
  ),
}).transform((v) => {
  return remap$(v, {
    "customer_lookup": "customerLookup",
    "failure_point": "failurePoint",
    "meter_matching": "meterMatching",
    "price_lookup": "priceLookup",
    "subscription_line_item_lookup": "subscriptionLineItemLookup",
  });
});

export function debugTrackerFromJSON(
  jsonString: string,
): SafeParseResult<DebugTracker, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DebugTracker$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DebugTracker' from JSON`,
  );
}
