/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeletePriceRequest = {
  endDate?: Date | undefined;
};

/** @internal */
export type DeletePriceRequest$Outbound = {
  end_date?: string | undefined;
};

/** @internal */
export const DeletePriceRequest$outboundSchema: z.ZodMiniType<
  DeletePriceRequest$Outbound,
  DeletePriceRequest
> = z.pipe(
  z.object({
    endDate: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      endDate: "end_date",
    });
  }),
);

export function deletePriceRequestToJSON(
  deletePriceRequest: DeletePriceRequest,
): string {
  return JSON.stringify(
    DeletePriceRequest$outboundSchema.parse(deletePriceRequest),
  );
}
