/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteTaxAssociationRequest = {
  /**
   * Tax Config ID
   */
  id: string;
};

/** @internal */
export type DeleteTaxAssociationRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTaxAssociationRequest$outboundSchema: z.ZodMiniType<
  DeleteTaxAssociationRequest$Outbound,
  DeleteTaxAssociationRequest
> = z.object({
  id: z.string(),
});

export function deleteTaxAssociationRequestToJSON(
  deleteTaxAssociationRequest: DeleteTaxAssociationRequest,
): string {
  return JSON.stringify(
    DeleteTaxAssociationRequest$outboundSchema.parse(
      deleteTaxAssociationRequest,
    ),
  );
}
