/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteFeatureRequest = {
  /**
   * Feature ID
   */
  id: string;
};

/** @internal */
export type DeleteFeatureRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteFeatureRequest$outboundSchema: z.ZodMiniType<
  DeleteFeatureRequest$Outbound,
  DeleteFeatureRequest
> = z.object({
  id: z.string(),
});

export function deleteFeatureRequestToJSON(
  deleteFeatureRequest: DeleteFeatureRequest,
): string {
  return JSON.stringify(
    DeleteFeatureRequest$outboundSchema.parse(deleteFeatureRequest),
  );
}
