/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteScheduledTaskRequest = {
  /**
   * Scheduled Task ID
   */
  id: string;
};

/** @internal */
export type DeleteScheduledTaskRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteScheduledTaskRequest$outboundSchema: z.ZodType<
  DeleteScheduledTaskRequest$Outbound,
  z.ZodTypeDef,
  DeleteScheduledTaskRequest
> = z.object({
  id: z.string(),
});

export function deleteScheduledTaskRequestToJSON(
  deleteScheduledTaskRequest: DeleteScheduledTaskRequest,
): string {
  return JSON.stringify(
    DeleteScheduledTaskRequest$outboundSchema.parse(deleteScheduledTaskRequest),
  );
}
