/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteGroupRequest = {
  /**
   * Group ID
   */
  id: string;
};

/** @internal */
export type DeleteGroupRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteGroupRequest$outboundSchema: z.ZodMiniType<
  DeleteGroupRequest$Outbound,
  DeleteGroupRequest
> = z.object({
  id: z.string(),
});

export function deleteGroupRequestToJSON(
  deleteGroupRequest: DeleteGroupRequest,
): string {
  return JSON.stringify(
    DeleteGroupRequest$outboundSchema.parse(deleteGroupRequest),
  );
}
