/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeletePlanRequest = {
  /**
   * Plan ID
   */
  id: string;
};

/** @internal */
export type DeletePlanRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeletePlanRequest$outboundSchema: z.ZodType<
  DeletePlanRequest$Outbound,
  z.ZodTypeDef,
  DeletePlanRequest
> = z.object({
  id: z.string(),
});

export function deletePlanRequestToJSON(
  deletePlanRequest: DeletePlanRequest,
): string {
  return JSON.stringify(
    DeletePlanRequest$outboundSchema.parse(deletePlanRequest),
  );
}
