/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  DeleteCreditGrantRequest,
  DeleteCreditGrantRequest$Outbound,
  DeleteCreditGrantRequest$outboundSchema,
} from "./deletecreditgrantrequest.js";

export type DeleteCreditGrantRequestRequest = {
  /**
   * Credit Grant ID
   */
  id: string;
  /**
   * Optional: effective_date for subscription-scoped grants
   */
  body?: DeleteCreditGrantRequest | undefined;
};

/** @internal */
export type DeleteCreditGrantRequestRequest$Outbound = {
  id: string;
  body?: DeleteCreditGrantRequest$Outbound | undefined;
};

/** @internal */
export const DeleteCreditGrantRequestRequest$outboundSchema: z.ZodType<
  DeleteCreditGrantRequestRequest$Outbound,
  z.ZodTypeDef,
  DeleteCreditGrantRequestRequest
> = z.object({
  id: z.string(),
  body: DeleteCreditGrantRequest$outboundSchema.optional(),
});

export function deleteCreditGrantRequestRequestToJSON(
  deleteCreditGrantRequestRequest: DeleteCreditGrantRequestRequest,
): string {
  return JSON.stringify(
    DeleteCreditGrantRequestRequest$outboundSchema.parse(
      deleteCreditGrantRequestRequest,
    ),
  );
}
