/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteServiceAccountRequest = {
  /**
   * Service Account ID
   */
  id: string;
};

/** @internal */
export type DeleteServiceAccountRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteServiceAccountRequest$outboundSchema: z.ZodMiniType<
  DeleteServiceAccountRequest$Outbound,
  DeleteServiceAccountRequest
> = z.object({
  id: z.string(),
});

export function deleteServiceAccountRequestToJSON(
  deleteServiceAccountRequest: DeleteServiceAccountRequest,
): string {
  return JSON.stringify(
    DeleteServiceAccountRequest$outboundSchema.parse(
      deleteServiceAccountRequest,
    ),
  );
}
