/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  DeletePriceRequest,
  DeletePriceRequest$Outbound,
  DeletePriceRequest$outboundSchema,
} from "./delete-price-request.js";

export type DeletePriceRequestRequest = {
  /**
   * Price ID
   */
  id: string;
  /**
   * Delete Price Request
   */
  body: DeletePriceRequest;
};

/** @internal */
export type DeletePriceRequestRequest$Outbound = {
  id: string;
  body: DeletePriceRequest$Outbound;
};

/** @internal */
export const DeletePriceRequestRequest$outboundSchema: z.ZodMiniType<
  DeletePriceRequestRequest$Outbound,
  DeletePriceRequestRequest
> = z.object({
  id: z.string(),
  body: DeletePriceRequest$outboundSchema,
});

export function deletePriceRequestRequestToJSON(
  deletePriceRequestRequest: DeletePriceRequestRequest,
): string {
  return JSON.stringify(
    DeletePriceRequestRequest$outboundSchema.parse(deletePriceRequestRequest),
  );
}
