/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const EntitlementSourceEntityType = {
  Plan: "plan",
  Addon: "addon",
  Subscription: "subscription",
} as const;
export type EntitlementSourceEntityType = OpenEnum<
  typeof EntitlementSourceEntityType
>;

/** @internal */
export const EntitlementSourceEntityType$inboundSchema: z.ZodType<
  EntitlementSourceEntityType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(EntitlementSourceEntityType);
