/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const EntitlementUsageResetPeriod = {
  Monthly: "MONTHLY",
  Annual: "ANNUAL",
  Weekly: "WEEKLY",
  Daily: "DAILY",
  Quarterly: "QUARTERLY",
  HalfYearly: "HALF_YEARLY",
  Never: "NEVER",
} as const;
export type EntitlementUsageResetPeriod = OpenEnum<
  typeof EntitlementUsageResetPeriod
>;

/** @internal */
export const EntitlementUsageResetPeriod$inboundSchema: z.ZodMiniType<
  EntitlementUsageResetPeriod,
  unknown
> = openEnums.inboundSchema(EntitlementUsageResetPeriod);
/** @internal */
export const EntitlementUsageResetPeriod$outboundSchema: z.ZodMiniType<
  string,
  EntitlementUsageResetPeriod
> = openEnums.outboundSchema(EntitlementUsageResetPeriod);
