/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const EnvironmentType = {
  Development: "development",
  Production: "production",
} as const;
export type EnvironmentType = ClosedEnum<typeof EnvironmentType>;

/** @internal */
export const EnvironmentType$outboundSchema: z.ZodNativeEnum<
  typeof EnvironmentType
> = z.nativeEnum(EnvironmentType);
