/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { ErrorCode, ErrorCode$inboundSchema } from "./errorcode.js";
import { TirdadError } from "./tirdaderror.js";

export type ErrorsErrorResponseData = {
  code?: ErrorCode | undefined;
  httpStatusCode?: number | undefined;
  message?: string | undefined;
};

export class ErrorsErrorResponse extends TirdadError {
  code?: ErrorCode | undefined;
  httpStatusCode?: number | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorsErrorResponseData;

  constructor(
    err: ErrorsErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.httpStatusCode != null) this.httpStatusCode = err.httpStatusCode;

    this.name = "ErrorsErrorResponse";
  }
}

/** @internal */
export const ErrorsErrorResponse$inboundSchema: z.ZodType<
  ErrorsErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: types.optional(ErrorCode$inboundSchema),
  http_status_code: types.optional(types.number()),
  message: types.optional(types.string()),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "http_status_code": "httpStatusCode",
    });

    return new ErrorsErrorResponse(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
