/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { ErrorCode, ErrorCode$inboundSchema } from "./error-code.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ErrorResponse = {
  code?: ErrorCode | undefined;
  httpStatusCode?: number | undefined;
  message?: string | undefined;
};

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodMiniType<
  ErrorResponse,
  unknown
> = z.pipe(
  z.object({
    code: types.optional(ErrorCode$inboundSchema),
    http_status_code: types.optional(types.number()),
    message: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "http_status_code": "httpStatusCode",
    });
  }),
);

export function errorResponseFromJSON(
  jsonString: string,
): SafeParseResult<ErrorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorResponse' from JSON`,
  );
}
