/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const EventProcessingStatusType = {
  Processed: "processed",
  Processing: "processing",
  Failed: "failed",
} as const;
export type EventProcessingStatusType = OpenEnum<
  typeof EventProcessingStatusType
>;

/** @internal */
export const EventProcessingStatusType$inboundSchema: z.ZodType<
  EventProcessingStatusType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(EventProcessingStatusType);
