/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ExportMetadataEntityType = {
  Customer: "customer",
  Wallet: "wallet",
} as const;
export type ExportMetadataEntityType = OpenEnum<
  typeof ExportMetadataEntityType
>;

/** @internal */
export const ExportMetadataEntityType$inboundSchema: z.ZodType<
  ExportMetadataEntityType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ExportMetadataEntityType);
/** @internal */
export const ExportMetadataEntityType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ExportMetadataEntityType
> = openEnums.outboundSchema(ExportMetadataEntityType);
