/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { DataType, DataType$outboundSchema } from "./data-type.js";
import {
  FilterOperatorType,
  FilterOperatorType$outboundSchema,
} from "./filter-operator-type.js";
import { Value, Value$Outbound, Value$outboundSchema } from "./value.js";

export type FilterCondition = {
  dataType?: DataType | undefined;
  field?: string | undefined;
  operator?: FilterOperatorType | undefined;
  value?: Value | undefined;
};

/** @internal */
export type FilterCondition$Outbound = {
  data_type?: string | undefined;
  field?: string | undefined;
  operator?: string | undefined;
  value?: Value$Outbound | undefined;
};

/** @internal */
export const FilterCondition$outboundSchema: z.ZodMiniType<
  FilterCondition$Outbound,
  FilterCondition
> = z.pipe(
  z.object({
    dataType: z.optional(DataType$outboundSchema),
    field: z.optional(z.string()),
    operator: z.optional(FilterOperatorType$outboundSchema),
    value: z.optional(Value$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      dataType: "data_type",
    });
  }),
);

export function filterConditionToJSON(
  filterCondition: FilterCondition,
): string {
  return JSON.stringify(FilterCondition$outboundSchema.parse(filterCondition));
}
