/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetHuggingFaceBillingDataRequest = {
  requestIds: Array<string>;
};

/** @internal */
export type GetHuggingFaceBillingDataRequest$Outbound = {
  requestIds: Array<string>;
};

/** @internal */
export const GetHuggingFaceBillingDataRequest$outboundSchema: z.ZodMiniType<
  GetHuggingFaceBillingDataRequest$Outbound,
  GetHuggingFaceBillingDataRequest
> = z.object({
  requestIds: z.array(z.string()),
});

export function getHuggingFaceBillingDataRequestToJSON(
  getHuggingFaceBillingDataRequest: GetHuggingFaceBillingDataRequest,
): string {
  return JSON.stringify(
    GetHuggingFaceBillingDataRequest$outboundSchema.parse(
      getHuggingFaceBillingDataRequest,
    ),
  );
}
