/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetEventRequest = {
  /**
   * Event ID
   */
  id: string;
};

/** @internal */
export type GetEventRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEventRequest$outboundSchema: z.ZodMiniType<
  GetEventRequest$Outbound,
  GetEventRequest
> = z.object({
  id: z.string(),
});

export function getEventRequestToJSON(
  getEventRequest: GetEventRequest,
): string {
  return JSON.stringify(GetEventRequest$outboundSchema.parse(getEventRequest));
}
