/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetTaskRequest = {
  /**
   * Task ID
   */
  id: string;
};

/** @internal */
export type GetTaskRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTaskRequest$outboundSchema: z.ZodMiniType<
  GetTaskRequest$Outbound,
  GetTaskRequest
> = z.object({
  id: z.string(),
});

export function getTaskRequestToJSON(getTaskRequest: GetTaskRequest): string {
  return JSON.stringify(GetTaskRequest$outboundSchema.parse(getTaskRequest));
}
