/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetGroupRequest = {
  /**
   * Group ID
   */
  id: string;
};

/** @internal */
export type GetGroupRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetGroupRequest$outboundSchema: z.ZodMiniType<
  GetGroupRequest$Outbound,
  GetGroupRequest
> = z.object({
  id: z.string(),
});

export function getGroupRequestToJSON(
  getGroupRequest: GetGroupRequest,
): string {
  return JSON.stringify(GetGroupRequest$outboundSchema.parse(getGroupRequest));
}
