/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetPriceRequest = {
  /**
   * Price ID
   */
  id: string;
};

/** @internal */
export type GetPriceRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPriceRequest$outboundSchema: z.ZodMiniType<
  GetPriceRequest$Outbound,
  GetPriceRequest
> = z.object({
  id: z.string(),
});

export function getPriceRequestToJSON(
  getPriceRequest: GetPriceRequest,
): string {
  return JSON.stringify(GetPriceRequest$outboundSchema.parse(getPriceRequest));
}
