/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetPriceUnitByCodeRequest = {
  /**
   * Price unit code
   */
  code: string;
};

/** @internal */
export type GetPriceUnitByCodeRequest$Outbound = {
  code: string;
};

/** @internal */
export const GetPriceUnitByCodeRequest$outboundSchema: z.ZodMiniType<
  GetPriceUnitByCodeRequest$Outbound,
  GetPriceUnitByCodeRequest
> = z.object({
  code: z.string(),
});

export function getPriceUnitByCodeRequestToJSON(
  getPriceUnitByCodeRequest: GetPriceUnitByCodeRequest,
): string {
  return JSON.stringify(
    GetPriceUnitByCodeRequest$outboundSchema.parse(getPriceUnitByCodeRequest),
  );
}
