/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetRefundRequest = {
  /**
   * Refund ID
   */
  id: string;
};

/** @internal */
export type GetRefundRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetRefundRequest$outboundSchema: z.ZodMiniType<
  GetRefundRequest$Outbound,
  GetRefundRequest
> = z.object({
  id: z.string(),
});

export function getRefundRequestToJSON(
  getRefundRequest: GetRefundRequest,
): string {
  return JSON.stringify(
    GetRefundRequest$outboundSchema.parse(getRefundRequest),
  );
}
