/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetScheduledTaskRequest = {
  /**
   * Scheduled Task ID
   */
  id: string;
};

/** @internal */
export type GetScheduledTaskRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetScheduledTaskRequest$outboundSchema: z.ZodMiniType<
  GetScheduledTaskRequest$Outbound,
  GetScheduledTaskRequest
> = z.object({
  id: z.string(),
});

export function getScheduledTaskRequestToJSON(
  getScheduledTaskRequest: GetScheduledTaskRequest,
): string {
  return JSON.stringify(
    GetScheduledTaskRequest$outboundSchema.parse(getScheduledTaskRequest),
  );
}
