/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetPlanCreditGrantsRequest = {
  /**
   * Plan ID
   */
  id: string;
};

/** @internal */
export type GetPlanCreditGrantsRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPlanCreditGrantsRequest$outboundSchema: z.ZodMiniType<
  GetPlanCreditGrantsRequest$Outbound,
  GetPlanCreditGrantsRequest
> = z.object({
  id: z.string(),
});

export function getPlanCreditGrantsRequestToJSON(
  getPlanCreditGrantsRequest: GetPlanCreditGrantsRequest,
): string {
  return JSON.stringify(
    GetPlanCreditGrantsRequest$outboundSchema.parse(getPlanCreditGrantsRequest),
  );
}
