/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetWalletRequest = {
  /**
   * Wallet ID
   */
  id: string;
};

/** @internal */
export type GetWalletRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWalletRequest$outboundSchema: z.ZodMiniType<
  GetWalletRequest$Outbound,
  GetWalletRequest
> = z.object({
  id: z.string(),
});

export function getWalletRequestToJSON(
  getWalletRequest: GetWalletRequest,
): string {
  return JSON.stringify(
    GetWalletRequest$outboundSchema.parse(getWalletRequest),
  );
}
