/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetCustomerWalletsRequest = {
  /**
   * populated from x-max-live header, not query param
   */
  minus?: number | undefined;
  expand?: string | undefined;
  fromCache?: boolean | undefined;
  id?: string | undefined;
  includeRealTimeBalance?: boolean | undefined;
  lookupKey?: string | undefined;
};

/** @internal */
export type GetCustomerWalletsRequest$Outbound = {
  "-"?: number | undefined;
  expand?: string | undefined;
  from_cache: boolean;
  id?: string | undefined;
  include_real_time_balance: boolean;
  lookup_key?: string | undefined;
};

/** @internal */
export const GetCustomerWalletsRequest$outboundSchema: z.ZodType<
  GetCustomerWalletsRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerWalletsRequest
> = z.object({
  minus: z.number().int().optional(),
  expand: z.string().optional(),
  fromCache: z.boolean().default(false),
  id: z.string().optional(),
  includeRealTimeBalance: z.boolean().default(false),
  lookupKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    minus: "-",
    fromCache: "from_cache",
    includeRealTimeBalance: "include_real_time_balance",
    lookupKey: "lookup_key",
  });
});

export function getCustomerWalletsRequestToJSON(
  getCustomerWalletsRequest: GetCustomerWalletsRequest,
): string {
  return JSON.stringify(
    GetCustomerWalletsRequest$outboundSchema.parse(getCustomerWalletsRequest),
  );
}
