/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetCouponRequest = {
  /**
   * Coupon ID
   */
  id: string;
};

/** @internal */
export type GetCouponRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCouponRequest$outboundSchema: z.ZodType<
  GetCouponRequest$Outbound,
  z.ZodTypeDef,
  GetCouponRequest
> = z.object({
  id: z.string(),
});

export function getCouponRequestToJSON(
  getCouponRequest: GetCouponRequest,
): string {
  return JSON.stringify(
    GetCouponRequest$outboundSchema.parse(getCouponRequest),
  );
}
