/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetSubscriptionEntitlementsRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Feature IDs to filter by
   */
  featureIds?: Array<string> | undefined;
};

/** @internal */
export type GetSubscriptionEntitlementsRequest$Outbound = {
  id: string;
  feature_ids?: Array<string> | undefined;
};

/** @internal */
export const GetSubscriptionEntitlementsRequest$outboundSchema: z.ZodType<
  GetSubscriptionEntitlementsRequest$Outbound,
  z.ZodTypeDef,
  GetSubscriptionEntitlementsRequest
> = z.object({
  id: z.string(),
  featureIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    featureIds: "feature_ids",
  });
});

export function getSubscriptionEntitlementsRequestToJSON(
  getSubscriptionEntitlementsRequest: GetSubscriptionEntitlementsRequest,
): string {
  return JSON.stringify(
    GetSubscriptionEntitlementsRequest$outboundSchema.parse(
      getSubscriptionEntitlementsRequest,
    ),
  );
}
