/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetTenantByIdRequest = {
  /**
   * Tenant ID
   */
  id: string;
};

/** @internal */
export type GetTenantByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTenantByIdRequest$outboundSchema: z.ZodType<
  GetTenantByIdRequest$Outbound,
  z.ZodTypeDef,
  GetTenantByIdRequest
> = z.object({
  id: z.string(),
});

export function getTenantByIdRequestToJSON(
  getTenantByIdRequest: GetTenantByIdRequest,
): string {
  return JSON.stringify(
    GetTenantByIdRequest$outboundSchema.parse(getTenantByIdRequest),
  );
}
