/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetTaxAssociationRequest = {
  /**
   * Tax Config ID
   */
  id: string;
};

/** @internal */
export type GetTaxAssociationRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTaxAssociationRequest$outboundSchema: z.ZodType<
  GetTaxAssociationRequest$Outbound,
  z.ZodTypeDef,
  GetTaxAssociationRequest
> = z.object({
  id: z.string(),
});

export function getTaxAssociationRequestToJSON(
  getTaxAssociationRequest: GetTaxAssociationRequest,
): string {
  return JSON.stringify(
    GetTaxAssociationRequest$outboundSchema.parse(getTaxAssociationRequest),
  );
}
