/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AggregationType,
  AggregationType$outboundSchema,
} from "./aggregationtype.js";
import { WindowSize, WindowSize$outboundSchema } from "./windowsize.js";

export type GetUsageRequest = {
  aggregationType: AggregationType;
  /**
   * BillingAnchor enables custom monthly billing periods for usage aggregation.
   *
   * @remarks
   *
   * When to use:
   * - WindowSize = "MONTH" AND you need custom monthly periods (not calendar months)
   * - Subscription billing that doesn't align with calendar months
   * - Example: Customer signed up on 15th, so billing periods are 15th to 15th
   *
   * When NOT to use:
   * - WindowSize != "MONTH" (ignored for DAY, HOUR, WEEK, etc.)
   * - Standard calendar-based billing (1st to 1st of each month)
   *
   * Example values:
   * - "2024-03-05T14:30:45.123456789Z" (5th of each month at 2:30:45 PM)
   * - "2024-01-15T00:00:00Z" (15th of each month at midnight)
   * - "2024-02-29T12:00:00Z" (29th of each month at noon - handles leap years)
   */
  billingAnchor?: Date | undefined;
  bucketSize?: WindowSize | undefined;
  customerId?: string | undefined;
  endTime?: Date | undefined;
  eventName: string;
  externalCustomerId?: string | undefined;
  filters?: { [k: string]: Array<string> } | undefined;
  /**
   * GroupByProperty is the property name in event.properties to group by before aggregating.
   *
   * @remarks
   * When set, aggregation is applied per unique value of this property within each bucket,
   * then the per-group results are summed to produce the bucket total.
   */
  groupByProperty?: string | undefined;
  multiplier?: string | undefined;
  /**
   * will be empty/ignored in case of COUNT
   */
  propertyName?: string | undefined;
  startTime?: Date | undefined;
  windowSize?: WindowSize | undefined;
};

/** @internal */
export type GetUsageRequest$Outbound = {
  aggregation_type: string;
  billing_anchor?: string | undefined;
  bucket_size?: string | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  event_name: string;
  external_customer_id?: string | undefined;
  filters?: { [k: string]: Array<string> } | undefined;
  group_by_property?: string | undefined;
  multiplier?: string | undefined;
  property_name?: string | undefined;
  start_time?: string | undefined;
  window_size?: string | undefined;
};

/** @internal */
export const GetUsageRequest$outboundSchema: z.ZodType<
  GetUsageRequest$Outbound,
  z.ZodTypeDef,
  GetUsageRequest
> = z.object({
  aggregationType: AggregationType$outboundSchema,
  billingAnchor: z.date().transform(v => v.toISOString()).optional(),
  bucketSize: WindowSize$outboundSchema.optional(),
  customerId: z.string().optional(),
  endTime: z.date().transform(v => v.toISOString()).optional(),
  eventName: z.string(),
  externalCustomerId: z.string().optional(),
  filters: z.record(z.array(z.string())).optional(),
  groupByProperty: z.string().optional(),
  multiplier: z.string().optional(),
  propertyName: z.string().optional(),
  startTime: z.date().transform(v => v.toISOString()).optional(),
  windowSize: WindowSize$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    aggregationType: "aggregation_type",
    billingAnchor: "billing_anchor",
    bucketSize: "bucket_size",
    customerId: "customer_id",
    endTime: "end_time",
    eventName: "event_name",
    externalCustomerId: "external_customer_id",
    groupByProperty: "group_by_property",
    propertyName: "property_name",
    startTime: "start_time",
    windowSize: "window_size",
  });
});

export function getUsageRequestToJSON(
  getUsageRequest: GetUsageRequest,
): string {
  return JSON.stringify(GetUsageRequest$outboundSchema.parse(getUsageRequest));
}
