/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const InvoiceStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
  Skipped: "SKIPPED",
} as const;
export type InvoiceStatus = OpenEnum<typeof InvoiceStatus>;

/** @internal */
export const InvoiceStatus$inboundSchema: z.ZodMiniType<
  InvoiceStatus,
  unknown
> = openEnums.inboundSchema(InvoiceStatus);
/** @internal */
export const InvoiceStatus$outboundSchema: z.ZodMiniType<
  string,
  InvoiceStatus
> = openEnums.outboundSchema(InvoiceStatus);
