/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AddLineItemRequest,
  AddLineItemRequest$Outbound,
  AddLineItemRequest$outboundSchema,
} from "./add-line-item-request.js";
import {
  InvoiceModifyLineItemAction,
  InvoiceModifyLineItemAction$outboundSchema,
} from "./invoice-modify-line-item-action.js";
import {
  UpdateLineItemRequest,
  UpdateLineItemRequest$Outbound,
  UpdateLineItemRequest$outboundSchema,
} from "./update-line-item-request.js";

export type InvoiceModifyLineItemParams = {
  action: InvoiceModifyLineItemAction;
  /**
   * Required for action 'add'. Must contain at least one line item.
   */
  items?: Array<AddLineItemRequest> | undefined;
  /**
   * Required for action 'update' (one line item per call; edits are versioned, so the id changes).
   */
  lineItemId?: string | undefined;
  /**
   * Required for action 'remove'. Must contain at least one line item ID.
   */
  lineItemIds?: Array<string> | undefined;
  update?: UpdateLineItemRequest | undefined;
};

/** @internal */
export type InvoiceModifyLineItemParams$Outbound = {
  action: string;
  items?: Array<AddLineItemRequest$Outbound> | undefined;
  line_item_id?: string | undefined;
  line_item_ids?: Array<string> | undefined;
  update?: UpdateLineItemRequest$Outbound | undefined;
};

/** @internal */
export const InvoiceModifyLineItemParams$outboundSchema: z.ZodMiniType<
  InvoiceModifyLineItemParams$Outbound,
  InvoiceModifyLineItemParams
> = z.pipe(
  z.object({
    action: InvoiceModifyLineItemAction$outboundSchema,
    items: z.optional(z.array(AddLineItemRequest$outboundSchema)),
    lineItemId: z.optional(z.string()),
    lineItemIds: z.optional(z.array(z.string())),
    update: z.optional(UpdateLineItemRequest$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      lineItemId: "line_item_id",
      lineItemIds: "line_item_ids",
    });
  }),
);

export function invoiceModifyLineItemParamsToJSON(
  invoiceModifyLineItemParams: InvoiceModifyLineItemParams,
): string {
  return JSON.stringify(
    InvoiceModifyLineItemParams$outboundSchema.parse(
      invoiceModifyLineItemParams,
    ),
  );
}
