/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  IntegrationEntityType,
  IntegrationEntityType$outboundSchema,
} from "./integration-entity-type.js";

export type LinkIntegrationMappingRequest = {
  entityId: string;
  entityType: IntegrationEntityType;
  metadata?: { [k: string]: any } | undefined;
  providerEntityId: string;
  providerType: string;
};

/** @internal */
export type LinkIntegrationMappingRequest$Outbound = {
  entity_id: string;
  entity_type: string;
  metadata?: { [k: string]: any } | undefined;
  provider_entity_id: string;
  provider_type: string;
};

/** @internal */
export const LinkIntegrationMappingRequest$outboundSchema: z.ZodMiniType<
  LinkIntegrationMappingRequest$Outbound,
  LinkIntegrationMappingRequest
> = z.pipe(
  z.object({
    entityId: z.string(),
    entityType: IntegrationEntityType$outboundSchema,
    metadata: z.optional(z.record(z.string(), z.any())),
    providerEntityId: z.string(),
    providerType: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      entityId: "entity_id",
      entityType: "entity_type",
      providerEntityId: "provider_entity_id",
      providerType: "provider_type",
    });
  }),
);

export function linkIntegrationMappingRequestToJSON(
  linkIntegrationMappingRequest: LinkIntegrationMappingRequest,
): string {
  return JSON.stringify(
    LinkIntegrationMappingRequest$outboundSchema.parse(
      linkIntegrationMappingRequest,
    ),
  );
}
