/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListScheduledTasksRequest = {
  /**
   * Limit
   */
  limit?: number | undefined;
  /**
   * Offset
   */
  offset?: number | undefined;
  /**
   * Filter by connection ID
   */
  connectionId?: string | undefined;
  /**
   * Filter by entity type
   */
  entityType?: string | undefined;
  /**
   * Filter by interval
   */
  interval?: string | undefined;
  /**
   * Filter by enabled status
   */
  enabled?: boolean | undefined;
};

/** @internal */
export type ListScheduledTasksRequest$Outbound = {
  limit?: number | undefined;
  offset?: number | undefined;
  connection_id?: string | undefined;
  entity_type?: string | undefined;
  interval?: string | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const ListScheduledTasksRequest$outboundSchema: z.ZodType<
  ListScheduledTasksRequest$Outbound,
  z.ZodTypeDef,
  ListScheduledTasksRequest
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  connectionId: z.string().optional(),
  entityType: z.string().optional(),
  interval: z.string().optional(),
  enabled: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    connectionId: "connection_id",
    entityType: "entity_type",
  });
});

export function listScheduledTasksRequestToJSON(
  listScheduledTasksRequest: ListScheduledTasksRequest,
): string {
  return JSON.stringify(
    ListScheduledTasksRequest$outboundSchema.parse(listScheduledTasksRequest),
  );
}
