/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  WalletResponse,
  WalletResponse$inboundSchema,
} from "./wallet-response.js";

export type ListResponseDtoWalletResponse = {
  items?: Array<WalletResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListResponseDtoWalletResponse$inboundSchema: z.ZodMiniType<
  ListResponseDtoWalletResponse,
  unknown
> = z.object({
  items: types.optional(z.array(WalletResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listResponseDtoWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListResponseDtoWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListResponseDtoWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListResponseDtoWalletResponse' from JSON`,
  );
}
