/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import {
  PriceUnitResponse,
  PriceUnitResponse$inboundSchema,
} from "./priceunitresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ListPriceUnitsResponse = {
  items?: Array<PriceUnitResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListPriceUnitsResponse$inboundSchema: z.ZodType<
  ListPriceUnitsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: types.optional(z.array(PriceUnitResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listPriceUnitsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPriceUnitsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPriceUnitsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPriceUnitsResponse' from JSON`,
  );
}
