/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListScheduledTasksRequest = {
  /**
   * Limit
   */
  limit?: number | undefined;
  /**
   * Offset
   */
  offset?: number | undefined;
  /**
   * Filter by connection ID
   */
  connectionId?: string | undefined;
  /**
   * Filter by entity type
   */
  entityType?: string | undefined;
  /**
   * Filter by interval
   */
  interval?: string | undefined;
  /**
   * Filter by enabled status
   */
  enabled?: boolean | undefined;
};

/** @internal */
export type ListScheduledTasksRequest$Outbound = {
  limit?: number | undefined;
  offset?: number | undefined;
  connection_id?: string | undefined;
  entity_type?: string | undefined;
  interval?: string | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const ListScheduledTasksRequest$outboundSchema: z.ZodMiniType<
  ListScheduledTasksRequest$Outbound,
  ListScheduledTasksRequest
> = z.pipe(
  z.object({
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    connectionId: z.optional(z.string()),
    entityType: z.optional(z.string()),
    interval: z.optional(z.string()),
    enabled: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      connectionId: "connection_id",
      entityType: "entity_type",
    });
  }),
);

export function listScheduledTasksRequestToJSON(
  listScheduledTasksRequest: ListScheduledTasksRequest,
): string {
  return JSON.stringify(
    ListScheduledTasksRequest$outboundSchema.parse(listScheduledTasksRequest),
  );
}
