/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  FeatureResponse,
  FeatureResponse$inboundSchema,
} from "./featureresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ListFeaturesResponse = {
  items?: Array<FeatureResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListFeaturesResponse$inboundSchema: z.ZodType<
  ListFeaturesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: types.optional(z.array(FeatureResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listFeaturesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListFeaturesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFeaturesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFeaturesResponse' from JSON`,
  );
}
