/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import {
  PaymentResponse,
  PaymentResponse$inboundSchema,
} from "./paymentresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ListPaymentsResponse = {
  items?: Array<PaymentResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListPaymentsResponse$inboundSchema: z.ZodType<
  ListPaymentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: types.optional(z.array(PaymentResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listPaymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPaymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPaymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPaymentsResponse' from JSON`,
  );
}
