/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  CouponAssociationResponse,
  CouponAssociationResponse$inboundSchema,
} from "./coupon-association-response.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ListCouponAssociationsResponse = {
  items?: Array<CouponAssociationResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListCouponAssociationsResponse$inboundSchema: z.ZodMiniType<
  ListCouponAssociationsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(CouponAssociationResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listCouponAssociationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCouponAssociationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCouponAssociationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCouponAssociationsResponse' from JSON`,
  );
}
