/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./pagination-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SubscriptionLineItemResponse,
  SubscriptionLineItemResponse$inboundSchema,
} from "./subscription-line-item-response.js";

export type ListSubscriptionLineItemsResponse = {
  items?: Array<SubscriptionLineItemResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListSubscriptionLineItemsResponse$inboundSchema: z.ZodMiniType<
  ListSubscriptionLineItemsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(SubscriptionLineItemResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listSubscriptionLineItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSubscriptionLineItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSubscriptionLineItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSubscriptionLineItemsResponse' from JSON`,
  );
}
