/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  EntitlementResponse,
  EntitlementResponse$inboundSchema,
} from "./entitlementresponse.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ListEntitlementsResponse = {
  items?: Array<EntitlementResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListEntitlementsResponse$inboundSchema: z.ZodType<
  ListEntitlementsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: types.optional(z.array(EntitlementResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listEntitlementsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEntitlementsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEntitlementsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEntitlementsResponse' from JSON`,
  );
}
