/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListRefundsRequest = {
  /**
   * Filter by invoice IDs
   */
  invoiceIds?: Array<string> | undefined;
  /**
   * Filter by payment IDs
   */
  paymentIds?: Array<string> | undefined;
  /**
   * Filter by credit note IDs
   */
  creditNoteIds?: Array<string> | undefined;
  /**
   * Filter by refund status
   */
  refundStatuses?: Array<string> | undefined;
  /**
   * Filter by refund destination
   */
  refundDestinations?: Array<string> | undefined;
  /**
   * Filter by payment gateway
   */
  gateway?: string | undefined;
  /**
   * Only refunds that have settled
   */
  onlySettled?: boolean | undefined;
  /**
   * Limit
   */
  limit?: number | undefined;
  /**
   * Offset
   */
  offset?: number | undefined;
};

/** @internal */
export type ListRefundsRequest$Outbound = {
  invoice_ids?: Array<string> | undefined;
  payment_ids?: Array<string> | undefined;
  credit_note_ids?: Array<string> | undefined;
  refund_statuses?: Array<string> | undefined;
  refund_destinations?: Array<string> | undefined;
  gateway?: string | undefined;
  only_settled?: boolean | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const ListRefundsRequest$outboundSchema: z.ZodMiniType<
  ListRefundsRequest$Outbound,
  ListRefundsRequest
> = z.pipe(
  z.object({
    invoiceIds: z.optional(z.array(z.string())),
    paymentIds: z.optional(z.array(z.string())),
    creditNoteIds: z.optional(z.array(z.string())),
    refundStatuses: z.optional(z.array(z.string())),
    refundDestinations: z.optional(z.array(z.string())),
    gateway: z.optional(z.string()),
    onlySettled: z.optional(z.boolean()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      invoiceIds: "invoice_ids",
      paymentIds: "payment_ids",
      creditNoteIds: "credit_note_ids",
      refundStatuses: "refund_statuses",
      refundDestinations: "refund_destinations",
      onlySettled: "only_settled",
    });
  }),
);

export function listRefundsRequestToJSON(
  listRefundsRequest: ListRefundsRequest,
): string {
  return JSON.stringify(
    ListRefundsRequest$outboundSchema.parse(listRefundsRequest),
  );
}
