/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListSubscriptionSchedulesRequest = {
  /**
   * Subscription ID
   */
  id: string;
};

/** @internal */
export type ListSubscriptionSchedulesRequest$Outbound = {
  id: string;
};

/** @internal */
export const ListSubscriptionSchedulesRequest$outboundSchema: z.ZodMiniType<
  ListSubscriptionSchedulesRequest$Outbound,
  ListSubscriptionSchedulesRequest
> = z.object({
  id: z.string(),
});

export function listSubscriptionSchedulesRequestToJSON(
  listSubscriptionSchedulesRequest: ListSubscriptionSchedulesRequest,
): string {
  return JSON.stringify(
    ListSubscriptionSchedulesRequest$outboundSchema.parse(
      listSubscriptionSchedulesRequest,
    ),
  );
}
