/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  PaginationResponse,
  PaginationResponse$inboundSchema,
} from "./paginationresponse.js";
import {
  ScheduledTaskResponse,
  ScheduledTaskResponse$inboundSchema,
} from "./scheduledtaskresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ListScheduledTasksResponse = {
  items?: Array<ScheduledTaskResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

/** @internal */
export const ListScheduledTasksResponse$inboundSchema: z.ZodType<
  ListScheduledTasksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: types.optional(z.array(ScheduledTaskResponse$inboundSchema)),
  pagination: types.optional(PaginationResponse$inboundSchema),
});

export function listScheduledTasksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListScheduledTasksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListScheduledTasksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListScheduledTasksResponse' from JSON`,
  );
}
