/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const MetadataCustomFieldSource = {
  Customer: "customer",
  Invoice: "invoice",
} as const;
export type MetadataCustomFieldSource = OpenEnum<
  typeof MetadataCustomFieldSource
>;

/** @internal */
export const MetadataCustomFieldSource$inboundSchema: z.ZodMiniType<
  MetadataCustomFieldSource,
  unknown
> = openEnums.inboundSchema(MetadataCustomFieldSource);
