/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const PaymentMethodType = {
  Card: "CARD",
  Ach: "ACH",
  Offline: "OFFLINE",
  Credits: "CREDITS",
  PaymentLink: "PAYMENT_LINK",
} as const;
export type PaymentMethodType = OpenEnum<typeof PaymentMethodType>;

/** @internal */
export const PaymentMethodType$inboundSchema: z.ZodType<
  PaymentMethodType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PaymentMethodType);
/** @internal */
export const PaymentMethodType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  PaymentMethodType
> = openEnums.outboundSchema(PaymentMethodType);
