/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  FilterCondition,
  FilterCondition$Outbound,
  FilterCondition$outboundSchema,
} from "./filtercondition.js";
import {
  SortCondition,
  SortCondition$Outbound,
  SortCondition$outboundSchema,
} from "./sortcondition.js";
import { Status, Status$outboundSchema } from "./status.js";

export const PlanFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type PlanFilterOrder = ClosedEnum<typeof PlanFilterOrder>;

export type PlanFilter = {
  endTime?: Date | undefined;
  expand?: string | undefined;
  /**
   * filters allows complex filtering based on multiple fields
   */
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  offset?: number | undefined;
  order?: PlanFilterOrder | undefined;
  planIds?: Array<string> | undefined;
  sort?: Array<SortCondition> | undefined;
  startTime?: Date | undefined;
  status?: Status | undefined;
};

/** @internal */
export const PlanFilterOrder$outboundSchema: z.ZodNativeEnum<
  typeof PlanFilterOrder
> = z.nativeEnum(PlanFilterOrder);

/** @internal */
export type PlanFilter$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<FilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  plan_ids?: Array<string> | undefined;
  sort?: Array<SortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const PlanFilter$outboundSchema: z.ZodType<
  PlanFilter$Outbound,
  z.ZodTypeDef,
  PlanFilter
> = z.object({
  endTime: z.date().transform(v => v.toISOString()).optional(),
  expand: z.string().optional(),
  filters: z.array(FilterCondition$outboundSchema).optional(),
  limit: z.number().int().optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  offset: z.number().int().optional(),
  order: PlanFilterOrder$outboundSchema.optional(),
  planIds: z.array(z.string()).optional(),
  sort: z.array(SortCondition$outboundSchema).optional(),
  startTime: z.date().transform(v => v.toISOString()).optional(),
  status: Status$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    lookupKey: "lookup_key",
    planIds: "plan_ids",
    startTime: "start_time",
  });
});

export function planFilterToJSON(planFilter: PlanFilter): string {
  return JSON.stringify(PlanFilter$outboundSchema.parse(planFilter));
}
