/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  ExecuteSubscriptionModifyRequest,
  ExecuteSubscriptionModifyRequest$Outbound,
  ExecuteSubscriptionModifyRequest$outboundSchema,
} from "./execute-subscription-modify-request.js";

export type PreviewSubscriptionModifyRequest = {
  /**
   * Subscription ID
   */
  id: string;
  /**
   * Modification preview request
   */
  body: ExecuteSubscriptionModifyRequest;
};

/** @internal */
export type PreviewSubscriptionModifyRequest$Outbound = {
  id: string;
  body: ExecuteSubscriptionModifyRequest$Outbound;
};

/** @internal */
export const PreviewSubscriptionModifyRequest$outboundSchema: z.ZodMiniType<
  PreviewSubscriptionModifyRequest$Outbound,
  PreviewSubscriptionModifyRequest
> = z.object({
  id: z.string(),
  body: ExecuteSubscriptionModifyRequest$outboundSchema,
});

export function previewSubscriptionModifyRequestToJSON(
  previewSubscriptionModifyRequest: PreviewSubscriptionModifyRequest,
): string {
  return JSON.stringify(
    PreviewSubscriptionModifyRequest$outboundSchema.parse(
      previewSubscriptionModifyRequest,
    ),
  );
}
