/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DebugTrackerStatus,
  DebugTrackerStatus$inboundSchema,
} from "./debugtrackerstatus.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "./errorresponse.js";
import { MatchedPrice, MatchedPrice$inboundSchema } from "./matchedprice.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type PriceLookupResult = {
  error?: ErrorResponse | undefined;
  matchedPrices?: Array<MatchedPrice> | undefined;
  status?: DebugTrackerStatus | undefined;
};

/** @internal */
export const PriceLookupResult$inboundSchema: z.ZodType<
  PriceLookupResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: types.optional(ErrorResponse$inboundSchema),
  matched_prices: types.optional(z.array(MatchedPrice$inboundSchema)),
  status: types.optional(DebugTrackerStatus$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "matched_prices": "matchedPrices",
  });
});

export function priceLookupResultFromJSON(
  jsonString: string,
): SafeParseResult<PriceLookupResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PriceLookupResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PriceLookupResult' from JSON`,
  );
}
