/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const PriceType = {
  Usage: "USAGE",
  Fixed: "FIXED",
} as const;
export type PriceType = OpenEnum<typeof PriceType>;

/** @internal */
export const PriceType$inboundSchema: z.ZodType<
  PriceType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PriceType);
/** @internal */
export const PriceType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  PriceType
> = openEnums.outboundSchema(PriceType);
