/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CreatePriceTier,
  CreatePriceTier$Outbound,
  CreatePriceTier$outboundSchema,
} from "./create-price-tier.js";

export type PriceUnitConfig = {
  amount?: string | undefined;
  priceUnit: string;
  priceUnitTiers?: Array<CreatePriceTier> | undefined;
};

/** @internal */
export type PriceUnitConfig$Outbound = {
  amount?: string | undefined;
  price_unit: string;
  price_unit_tiers?: Array<CreatePriceTier$Outbound> | undefined;
};

/** @internal */
export const PriceUnitConfig$outboundSchema: z.ZodMiniType<
  PriceUnitConfig$Outbound,
  PriceUnitConfig
> = z.pipe(
  z.object({
    amount: z.optional(z.string()),
    priceUnit: z.string(),
    priceUnitTiers: z.optional(z.array(CreatePriceTier$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      priceUnit: "price_unit",
      priceUnitTiers: "price_unit_tiers",
    });
  }),
);

export function priceUnitConfigToJSON(
  priceUnitConfig: PriceUnitConfig,
): string {
  return JSON.stringify(PriceUnitConfig$outboundSchema.parse(priceUnitConfig));
}
