/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  FilterCondition,
  FilterCondition$Outbound,
  FilterCondition$outboundSchema,
} from "./filtercondition.js";
import {
  SortCondition,
  SortCondition$Outbound,
  SortCondition$outboundSchema,
} from "./sortcondition.js";
import { Status, Status$outboundSchema } from "./status.js";

export const PriceUnitFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type PriceUnitFilterOrder = ClosedEnum<typeof PriceUnitFilterOrder>;

export type PriceUnitFilter = {
  endTime?: Date | undefined;
  expand?: string | undefined;
  /**
   * filters allows complex filtering based on multiple fields
   */
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: PriceUnitFilterOrder | undefined;
  priceUnitIds?: Array<string> | undefined;
  sort?: Array<SortCondition> | undefined;
  startTime?: Date | undefined;
  status?: Status | undefined;
};

/** @internal */
export const PriceUnitFilterOrder$outboundSchema: z.ZodNativeEnum<
  typeof PriceUnitFilterOrder
> = z.nativeEnum(PriceUnitFilterOrder);

/** @internal */
export type PriceUnitFilter$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<FilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  price_unit_ids?: Array<string> | undefined;
  sort?: Array<SortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const PriceUnitFilter$outboundSchema: z.ZodType<
  PriceUnitFilter$Outbound,
  z.ZodTypeDef,
  PriceUnitFilter
> = z.object({
  endTime: z.date().transform(v => v.toISOString()).optional(),
  expand: z.string().optional(),
  filters: z.array(FilterCondition$outboundSchema).optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  order: PriceUnitFilterOrder$outboundSchema.optional(),
  priceUnitIds: z.array(z.string()).optional(),
  sort: z.array(SortCondition$outboundSchema).optional(),
  startTime: z.date().transform(v => v.toISOString()).optional(),
  status: Status$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    endTime: "end_time",
    priceUnitIds: "price_unit_ids",
    startTime: "start_time",
  });
});

export function priceUnitFilterToJSON(
  priceUnitFilter: PriceUnitFilter,
): string {
  return JSON.stringify(PriceUnitFilter$outboundSchema.parse(priceUnitFilter));
}
