/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
  FilterCondition,
  FilterCondition$Outbound,
  FilterCondition$outboundSchema,
} from "./filter-condition.js";
import {
  SortCondition,
  SortCondition$Outbound,
  SortCondition$outboundSchema,
} from "./sort-condition.js";
import { Status, Status$outboundSchema } from "./status.js";

export const PriceUnitFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type PriceUnitFilterOrder = ClosedEnum<typeof PriceUnitFilterOrder>;

export type PriceUnitFilter = {
  endTime?: Date | undefined;
  expand?: string | undefined;
  /**
   * filters allows complex filtering based on multiple fields
   */
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: PriceUnitFilterOrder | undefined;
  priceUnitIds?: Array<string> | undefined;
  sort?: Array<SortCondition> | undefined;
  startTime?: Date | undefined;
  status?: Status | undefined;
};

/** @internal */
export const PriceUnitFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof PriceUnitFilterOrder
> = z.enum(PriceUnitFilterOrder);

/** @internal */
export type PriceUnitFilter$Outbound = {
  end_time?: string | undefined;
  expand?: string | undefined;
  filters?: Array<FilterCondition$Outbound> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  price_unit_ids?: Array<string> | undefined;
  sort?: Array<SortCondition$Outbound> | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const PriceUnitFilter$outboundSchema: z.ZodMiniType<
  PriceUnitFilter$Outbound,
  PriceUnitFilter
> = z.pipe(
  z.object({
    endTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    expand: z.optional(z.string()),
    filters: z.optional(z.array(FilterCondition$outboundSchema)),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(PriceUnitFilterOrder$outboundSchema),
    priceUnitIds: z.optional(z.array(z.string())),
    sort: z.optional(z.array(SortCondition$outboundSchema)),
    startTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    status: z.optional(Status$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      endTime: "end_time",
      priceUnitIds: "price_unit_ids",
      startTime: "start_time",
    });
  }),
);

export function priceUnitFilterToJSON(
  priceUnitFilter: PriceUnitFilter,
): string {
  return JSON.stringify(PriceUnitFilter$outboundSchema.parse(priceUnitFilter));
}
