/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CreatePriceTier,
  CreatePriceTier$Outbound,
  CreatePriceTier$outboundSchema,
} from "./createpricetier.js";

export type PriceUnitConfig = {
  amount?: string | undefined;
  priceUnit: string;
  priceUnitTiers?: Array<CreatePriceTier> | undefined;
};

/** @internal */
export type PriceUnitConfig$Outbound = {
  amount?: string | undefined;
  price_unit: string;
  price_unit_tiers?: Array<CreatePriceTier$Outbound> | undefined;
};

/** @internal */
export const PriceUnitConfig$outboundSchema: z.ZodType<
  PriceUnitConfig$Outbound,
  z.ZodTypeDef,
  PriceUnitConfig
> = z.object({
  amount: z.string().optional(),
  priceUnit: z.string(),
  priceUnitTiers: z.array(CreatePriceTier$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    priceUnit: "price_unit",
    priceUnitTiers: "price_unit_tiers",
  });
});

export function priceUnitConfigToJSON(
  priceUnitConfig: PriceUnitConfig,
): string {
  return JSON.stringify(PriceUnitConfig$outboundSchema.parse(priceUnitConfig));
}
