/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  FinalizeCreditNoteRequest,
  FinalizeCreditNoteRequest$Outbound,
  FinalizeCreditNoteRequest$outboundSchema,
} from "./finalize-credit-note-request.js";

export type ProcessCreditNoteRequest = {
  /**
   * Credit note ID
   */
  id: string;
  /**
   * Finalize options
   */
  body?: FinalizeCreditNoteRequest | undefined;
};

/** @internal */
export type ProcessCreditNoteRequest$Outbound = {
  id: string;
  body?: FinalizeCreditNoteRequest$Outbound | undefined;
};

/** @internal */
export const ProcessCreditNoteRequest$outboundSchema: z.ZodMiniType<
  ProcessCreditNoteRequest$Outbound,
  ProcessCreditNoteRequest
> = z.object({
  id: z.string(),
  body: z.optional(FinalizeCreditNoteRequest$outboundSchema),
});

export function processCreditNoteRequestToJSON(
  processCreditNoteRequest: ProcessCreditNoteRequest,
): string {
  return JSON.stringify(
    ProcessCreditNoteRequest$outboundSchema.parse(processCreditNoteRequest),
  );
}
