/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ProcessCreditNoteRequest = {
  /**
   * Credit note ID
   */
  id: string;
};

/** @internal */
export type ProcessCreditNoteRequest$Outbound = {
  id: string;
};

/** @internal */
export const ProcessCreditNoteRequest$outboundSchema: z.ZodMiniType<
  ProcessCreditNoteRequest$Outbound,
  ProcessCreditNoteRequest
> = z.object({
  id: z.string(),
});

export function processCreditNoteRequestToJSON(
  processCreditNoteRequest: ProcessCreditNoteRequest,
): string {
  return JSON.stringify(
    ProcessCreditNoteRequest$outboundSchema.parse(processCreditNoteRequest),
  );
}
