/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";
import { Status, Status$outboundSchema } from "./status.js";

export const QueryFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type QueryFilterOrder = ClosedEnum<typeof QueryFilterOrder>;

export type QueryFilter = {
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: QueryFilterOrder | undefined;
  sort?: string | undefined;
  status?: Status | undefined;
};

/** @internal */
export const QueryFilterOrder$outboundSchema: z.ZodMiniEnum<
  typeof QueryFilterOrder
> = z.enum(QueryFilterOrder);

/** @internal */
export type QueryFilter$Outbound = {
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  sort?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const QueryFilter$outboundSchema: z.ZodMiniType<
  QueryFilter$Outbound,
  QueryFilter
> = z.object({
  expand: z.optional(z.string()),
  limit: z.optional(z.int()),
  offset: z.optional(z.int()),
  order: z.optional(QueryFilterOrder$outboundSchema),
  sort: z.optional(z.string()),
  status: z.optional(Status$outboundSchema),
});

export function queryFilterToJSON(queryFilter: QueryFilter): string {
  return JSON.stringify(QueryFilter$outboundSchema.parse(queryFilter));
}
