/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  AWSMarketplaceAgreement,
  AWSMarketplaceAgreement$Outbound,
  AWSMarketplaceAgreement$outboundSchema,
} from "./aws-marketplace-agreement.js";
import {
  AzureMarketplaceAgreement,
  AzureMarketplaceAgreement$Outbound,
  AzureMarketplaceAgreement$outboundSchema,
} from "./azure-marketplace-agreement.js";
import {
  GCPMarketplaceAgreement,
  GCPMarketplaceAgreement$Outbound,
  GCPMarketplaceAgreement$outboundSchema,
} from "./gcp-marketplace-agreement.js";
import {
  SecretProvider,
  SecretProvider$outboundSchema,
} from "./secret-provider.js";

export type RegisterMarketplaceAgreementRequest = {
  aws?: AWSMarketplaceAgreement | undefined;
  azure?: AzureMarketplaceAgreement | undefined;
  customerId: string;
  gcp?: GCPMarketplaceAgreement | undefined;
  planId: string;
  provider: SecretProvider;
  subscriptionId: string;
};

/** @internal */
export type RegisterMarketplaceAgreementRequest$Outbound = {
  aws?: AWSMarketplaceAgreement$Outbound | undefined;
  azure?: AzureMarketplaceAgreement$Outbound | undefined;
  customer_id: string;
  gcp?: GCPMarketplaceAgreement$Outbound | undefined;
  plan_id: string;
  provider: string;
  subscription_id: string;
};

/** @internal */
export const RegisterMarketplaceAgreementRequest$outboundSchema: z.ZodMiniType<
  RegisterMarketplaceAgreementRequest$Outbound,
  RegisterMarketplaceAgreementRequest
> = z.pipe(
  z.object({
    aws: z.optional(AWSMarketplaceAgreement$outboundSchema),
    azure: z.optional(AzureMarketplaceAgreement$outboundSchema),
    customerId: z.string(),
    gcp: z.optional(GCPMarketplaceAgreement$outboundSchema),
    planId: z.string(),
    provider: SecretProvider$outboundSchema,
    subscriptionId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      customerId: "customer_id",
      planId: "plan_id",
      subscriptionId: "subscription_id",
    });
  }),
);

export function registerMarketplaceAgreementRequestToJSON(
  registerMarketplaceAgreementRequest: RegisterMarketplaceAgreementRequest,
): string {
  return JSON.stringify(
    RegisterMarketplaceAgreementRequest$outboundSchema.parse(
      registerMarketplaceAgreementRequest,
    ),
  );
}
