/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ResetUsage = {
  BillingPeriod: "BILLING_PERIOD",
  Never: "NEVER",
} as const;
export type ResetUsage = OpenEnum<typeof ResetUsage>;

/** @internal */
export const ResetUsage$inboundSchema: z.ZodType<
  ResetUsage,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ResetUsage);
/** @internal */
export const ResetUsage$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ResetUsage
> = openEnums.outboundSchema(ResetUsage);
