/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ResumeMode = {
  Immediate: "immediate",
  Scheduled: "scheduled",
  Auto: "auto",
} as const;
export type ResumeMode = OpenEnum<typeof ResumeMode>;

/** @internal */
export const ResumeMode$inboundSchema: z.ZodMiniType<ResumeMode, unknown> =
  openEnums.inboundSchema(ResumeMode);
