/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ScheduledTaskEntityType = {
  Events: "events",
  Invoice: "invoice",
  CreditTopups: "credit_topups",
  CreditUsage: "credit_usage",
  UsageAnalytics: "usage_analytics",
} as const;
export type ScheduledTaskEntityType = OpenEnum<typeof ScheduledTaskEntityType>;

/** @internal */
export const ScheduledTaskEntityType$inboundSchema: z.ZodType<
  ScheduledTaskEntityType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ScheduledTaskEntityType);
/** @internal */
export const ScheduledTaskEntityType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ScheduledTaskEntityType
> = openEnums.outboundSchema(ScheduledTaskEntityType);
