/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  SecretProvider,
  SecretProvider$inboundSchema,
} from "./secretprovider.js";
import { SecretType, SecretType$inboundSchema } from "./secrettype.js";
import { Status, Status$inboundSchema } from "./status.js";
import { UserType, UserType$inboundSchema } from "./usertype.js";

export type SecretResponse = {
  createdAt?: Date | undefined;
  displayId?: string | undefined;
  expiresAt?: Date | undefined;
  id?: string | undefined;
  lastUsedAt?: Date | undefined;
  name?: string | undefined;
  provider?: SecretProvider | undefined;
  /**
   * RBAC roles
   */
  roles?: Array<string> | undefined;
  status?: Status | undefined;
  type?: SecretType | undefined;
  updatedAt?: Date | undefined;
  userType?: UserType | undefined;
};

/** @internal */
export const SecretResponse$inboundSchema: z.ZodType<
  SecretResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  created_at: types.optional(types.date()),
  display_id: types.optional(types.string()),
  expires_at: types.optional(types.date()),
  id: types.optional(types.string()),
  last_used_at: types.optional(types.date()),
  name: types.optional(types.string()),
  provider: types.optional(SecretProvider$inboundSchema),
  roles: types.optional(z.array(types.string())),
  status: types.optional(Status$inboundSchema),
  type: types.optional(SecretType$inboundSchema),
  updated_at: types.optional(types.date()),
  user_type: types.optional(UserType$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "display_id": "displayId",
    "expires_at": "expiresAt",
    "last_used_at": "lastUsedAt",
    "updated_at": "updatedAt",
    "user_type": "userType",
  });
});

export function secretResponseFromJSON(
  jsonString: string,
): SafeParseResult<SecretResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecretResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecretResponse' from JSON`,
  );
}
