/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const SortDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type SortDirection = OpenEnum<typeof SortDirection>;

/** @internal */
export const SortDirection$inboundSchema: z.ZodMiniType<
  SortDirection,
  unknown
> = openEnums.inboundSchema(SortDirection);
/** @internal */
export const SortDirection$outboundSchema: z.ZodMiniType<
  string,
  SortDirection
> = openEnums.outboundSchema(SortDirection);
