/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const Status = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type Status = OpenEnum<typeof Status>;

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<Status, unknown> = openEnums
  .inboundSchema(Status);
/** @internal */
export const Status$outboundSchema: z.ZodMiniType<string, Status> = openEnums
  .outboundSchema(Status);
