/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  GroupedInvoicingAction,
  GroupedInvoicingAction$outboundSchema,
} from "./grouped-invoicing-action.js";

export type SubModifyGroupedInvoicingParams = {
  action: GroupedInvoicingAction;
  childSubscriptionIds?: Array<string> | undefined;
  /**
   * ParentSubscriptionID is required for action 'add'.
   */
  parentSubscriptionId?: string | undefined;
};

/** @internal */
export type SubModifyGroupedInvoicingParams$Outbound = {
  action: string;
  child_subscription_ids?: Array<string> | undefined;
  parent_subscription_id?: string | undefined;
};

/** @internal */
export const SubModifyGroupedInvoicingParams$outboundSchema: z.ZodMiniType<
  SubModifyGroupedInvoicingParams$Outbound,
  SubModifyGroupedInvoicingParams
> = z.pipe(
  z.object({
    action: GroupedInvoicingAction$outboundSchema,
    childSubscriptionIds: z.optional(z.array(z.string())),
    parentSubscriptionId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      childSubscriptionIds: "child_subscription_ids",
      parentSubscriptionId: "parent_subscription_id",
    });
  }),
);

export function subModifyGroupedInvoicingParamsToJSON(
  subModifyGroupedInvoicingParams: SubModifyGroupedInvoicingParams,
): string {
  return JSON.stringify(
    SubModifyGroupedInvoicingParams$outboundSchema.parse(
      subModifyGroupedInvoicingParams,
    ),
  );
}
