/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  GroupedInvoicingAction,
  GroupedInvoicingAction$outboundSchema,
} from "./groupedinvoicingaction.js";

export type SubModifyGroupedInvoicingParams = {
  action: GroupedInvoicingAction;
  childSubscriptionIds?: Array<string> | undefined;
  /**
   * ParentSubscriptionID is required for action 'add'.
   */
  parentSubscriptionId?: string | undefined;
};

/** @internal */
export type SubModifyGroupedInvoicingParams$Outbound = {
  action: string;
  child_subscription_ids?: Array<string> | undefined;
  parent_subscription_id?: string | undefined;
};

/** @internal */
export const SubModifyGroupedInvoicingParams$outboundSchema: z.ZodType<
  SubModifyGroupedInvoicingParams$Outbound,
  z.ZodTypeDef,
  SubModifyGroupedInvoicingParams
> = z.object({
  action: GroupedInvoicingAction$outboundSchema,
  childSubscriptionIds: z.array(z.string()).optional(),
  parentSubscriptionId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    childSubscriptionIds: "child_subscription_ids",
    parentSubscriptionId: "parent_subscription_id",
  });
});

export function subModifyGroupedInvoicingParamsToJSON(
  subModifyGroupedInvoicingParams: SubModifyGroupedInvoicingParams,
): string {
  return JSON.stringify(
    SubModifyGroupedInvoicingParams$outboundSchema.parse(
      subModifyGroupedInvoicingParams,
    ),
  );
}
