/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const SubscriptionType = {
  Standalone: "standalone",
  DelegatedInvoicing: "delegated_invoicing",
  Parent: "parent",
  Inherited: "inherited",
  GroupedInvoicing: "grouped_invoicing",
} as const;
export type SubscriptionType = OpenEnum<typeof SubscriptionType>;

/** @internal */
export const SubscriptionType$inboundSchema: z.ZodType<
  SubscriptionType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SubscriptionType);
/** @internal */
export const SubscriptionType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SubscriptionType
> = openEnums.outboundSchema(SubscriptionType);
