/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  DebugTrackerStatus,
  DebugTrackerStatus$inboundSchema,
} from "./debugtrackerstatus.js";
import { ErrorResponse, ErrorResponse$inboundSchema } from "./errorresponse.js";
import {
  MatchedSubscriptionLineItem,
  MatchedSubscriptionLineItem$inboundSchema,
} from "./matchedsubscriptionlineitem.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SubscriptionLineItemLookupResult = {
  error?: ErrorResponse | undefined;
  matchedLineItems?: Array<MatchedSubscriptionLineItem> | undefined;
  status?: DebugTrackerStatus | undefined;
};

/** @internal */
export const SubscriptionLineItemLookupResult$inboundSchema: z.ZodType<
  SubscriptionLineItemLookupResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: types.optional(ErrorResponse$inboundSchema),
  matched_line_items: types.optional(
    z.array(MatchedSubscriptionLineItem$inboundSchema),
  ),
  status: types.optional(DebugTrackerStatus$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "matched_line_items": "matchedLineItems",
  });
});

export function subscriptionLineItemLookupResultFromJSON(
  jsonString: string,
): SafeParseResult<SubscriptionLineItemLookupResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriptionLineItemLookupResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriptionLineItemLookupResult' from JSON`,
  );
}
