/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  EntitySyncConfig,
  EntitySyncConfig$inboundSchema,
} from "./entitysyncconfig.js";
import {
  InvoiceSyncSettings,
  InvoiceSyncSettings$inboundSchema,
} from "./invoicesyncsettings.js";
import {
  S3ExportConfig,
  S3ExportConfig$inboundSchema,
} from "./s3exportconfig.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type SyncConfig = {
  customer?: EntitySyncConfig | undefined;
  deal?: EntitySyncConfig | undefined;
  invoice?: EntitySyncConfig | undefined;
  invoiceSyncSettings?: InvoiceSyncSettings | undefined;
  payment?: EntitySyncConfig | undefined;
  plan?: EntitySyncConfig | undefined;
  quote?: EntitySyncConfig | undefined;
  s3?: S3ExportConfig | undefined;
  subscription?: EntitySyncConfig | undefined;
};

/** @internal */
export const SyncConfig$inboundSchema: z.ZodType<
  SyncConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer: types.optional(EntitySyncConfig$inboundSchema),
  deal: types.optional(EntitySyncConfig$inboundSchema),
  invoice: types.optional(EntitySyncConfig$inboundSchema),
  invoice_sync_settings: types.optional(InvoiceSyncSettings$inboundSchema),
  payment: types.optional(EntitySyncConfig$inboundSchema),
  plan: types.optional(EntitySyncConfig$inboundSchema),
  quote: types.optional(EntitySyncConfig$inboundSchema),
  s3: types.optional(S3ExportConfig$inboundSchema),
  subscription: types.optional(EntitySyncConfig$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "invoice_sync_settings": "invoiceSyncSettings",
  });
});

export function syncConfigFromJSON(
  jsonString: string,
): SafeParseResult<SyncConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SyncConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SyncConfig' from JSON`,
  );
}
