/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SyncPlanPricesRequest = {
  /**
   * Plan ID
   */
  id: string;
};

/** @internal */
export type SyncPlanPricesRequest$Outbound = {
  id: string;
};

/** @internal */
export const SyncPlanPricesRequest$outboundSchema: z.ZodType<
  SyncPlanPricesRequest$Outbound,
  z.ZodTypeDef,
  SyncPlanPricesRequest
> = z.object({
  id: z.string(),
});

export function syncPlanPricesRequestToJSON(
  syncPlanPricesRequest: SyncPlanPricesRequest,
): string {
  return JSON.stringify(
    SyncPlanPricesRequest$outboundSchema.parse(syncPlanPricesRequest),
  );
}
