/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const TaskType = {
  Import: "IMPORT",
  Export: "EXPORT",
} as const;
export type TaskType = OpenEnum<typeof TaskType>;

/** @internal */
export const TaskType$inboundSchema: z.ZodType<
  TaskType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(TaskType);
/** @internal */
export const TaskType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  TaskType
> = openEnums.outboundSchema(TaskType);
