/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { TaxBehavior, TaxBehavior$outboundSchema } from "./tax-behavior.js";

export type TaxAssociationUpdateRequest = {
  autoApply?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  taxBehavior?: TaxBehavior | undefined;
};

/** @internal */
export type TaxAssociationUpdateRequest$Outbound = {
  auto_apply?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  tax_behavior?: string | undefined;
};

/** @internal */
export const TaxAssociationUpdateRequest$outboundSchema: z.ZodMiniType<
  TaxAssociationUpdateRequest$Outbound,
  TaxAssociationUpdateRequest
> = z.pipe(
  z.object({
    autoApply: z.optional(z.boolean()),
    metadata: z.optional(z.record(z.string(), z.string())),
    priority: z.optional(z.int()),
    taxBehavior: z.optional(TaxBehavior$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      autoApply: "auto_apply",
      taxBehavior: "tax_behavior",
    });
  }),
);

export function taxAssociationUpdateRequestToJSON(
  taxAssociationUpdateRequest: TaxAssociationUpdateRequest,
): string {
  return JSON.stringify(
    TaxAssociationUpdateRequest$outboundSchema.parse(
      taxAssociationUpdateRequest,
    ),
  );
}
