/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const TaxRateType = {
  Percentage: "percentage",
} as const;
export type TaxRateType = ClosedEnum<typeof TaxRateType>;

/** @internal */
export const TaxRateType$inboundSchema: z.ZodMiniEnum<typeof TaxRateType> = z
  .enum(TaxRateType);
/** @internal */
export const TaxRateType$outboundSchema: z.ZodMiniEnum<typeof TaxRateType> =
  TaxRateType$inboundSchema;
