/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  CustomerUsageSummaryResponse,
  CustomerUsageSummaryResponse$inboundSchema,
} from "./customer-usage-summary-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$inboundSchema,
} from "./subscription-response.js";

export type TenantBillingUsage = {
  subscriptions?: Array<SubscriptionResponse> | undefined;
  usage?: CustomerUsageSummaryResponse | undefined;
};

/** @internal */
export const TenantBillingUsage$inboundSchema: z.ZodMiniType<
  TenantBillingUsage,
  unknown
> = z.object({
  subscriptions: types.optional(z.array(SubscriptionResponse$inboundSchema)),
  usage: types.optional(CustomerUsageSummaryResponse$inboundSchema),
});

export function tenantBillingUsageFromJSON(
  jsonString: string,
): SafeParseResult<TenantBillingUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TenantBillingUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TenantBillingUsage' from JSON`,
  );
}
