/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  TopUpWalletRequest,
  TopUpWalletRequest$Outbound,
  TopUpWalletRequest$outboundSchema,
} from "./top-up-wallet-request.js";

export type TopUpWalletRequestRequest = {
  /**
   * Wallet ID
   */
  id: string;
  /**
   * Top up request
   */
  body: TopUpWalletRequest;
};

/** @internal */
export type TopUpWalletRequestRequest$Outbound = {
  id: string;
  body: TopUpWalletRequest$Outbound;
};

/** @internal */
export const TopUpWalletRequestRequest$outboundSchema: z.ZodMiniType<
  TopUpWalletRequestRequest$Outbound,
  TopUpWalletRequestRequest
> = z.object({
  id: z.string(),
  body: TopUpWalletRequest$outboundSchema,
});

export function topUpWalletRequestRequestToJSON(
  topUpWalletRequestRequest: TopUpWalletRequestRequest,
): string {
  return JSON.stringify(
    TopUpWalletRequestRequest$outboundSchema.parse(topUpWalletRequestRequest),
  );
}
