/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  WalletResponse,
  WalletResponse$inboundSchema,
} from "./walletresponse.js";
import {
  WalletTransactionResponse,
  WalletTransactionResponse$inboundSchema,
} from "./wallettransactionresponse.js";

export type TopUpWalletResponse = {
  /**
   * Invoice ID if an invoice was created (only for PURCHASED_CREDIT_INVOICED)
   */
  invoiceId?: string | undefined;
  wallet?: WalletResponse | undefined;
  walletTransaction?: WalletTransactionResponse | undefined;
};

/** @internal */
export const TopUpWalletResponse$inboundSchema: z.ZodType<
  TopUpWalletResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  invoice_id: types.optional(types.string()),
  wallet: types.optional(WalletResponse$inboundSchema),
  wallet_transaction: types.optional(WalletTransactionResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "invoice_id": "invoiceId",
    "wallet_transaction": "walletTransaction",
  });
});

export function topUpWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<TopUpWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopUpWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopUpWalletResponse' from JSON`,
  );
}
