/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const TrialEndAction = {
  Immediate: "immediate",
  ScheduledDate: "scheduled_date",
} as const;
export type TrialEndAction = ClosedEnum<typeof TrialEndAction>;

/** @internal */
export const TrialEndAction$outboundSchema: z.ZodMiniEnum<
  typeof TrialEndAction
> = z.enum(TrialEndAction);
