/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TriggerForceRunRequest,
  TriggerForceRunRequest$Outbound,
  TriggerForceRunRequest$outboundSchema,
} from "./triggerforcerunrequest.js";

export type TriggerScheduledTaskRunRequest = {
  /**
   * Scheduled Task ID
   */
  id: string;
  /**
   * Optional start and end time for custom range
   */
  body?: TriggerForceRunRequest | undefined;
};

/** @internal */
export type TriggerScheduledTaskRunRequest$Outbound = {
  id: string;
  body?: TriggerForceRunRequest$Outbound | undefined;
};

/** @internal */
export const TriggerScheduledTaskRunRequest$outboundSchema: z.ZodType<
  TriggerScheduledTaskRunRequest$Outbound,
  z.ZodTypeDef,
  TriggerScheduledTaskRunRequest
> = z.object({
  id: z.string(),
  body: TriggerForceRunRequest$outboundSchema.optional(),
});

export function triggerScheduledTaskRunRequestToJSON(
  triggerScheduledTaskRunRequest: TriggerScheduledTaskRunRequest,
): string {
  return JSON.stringify(
    TriggerScheduledTaskRunRequest$outboundSchema.parse(
      triggerScheduledTaskRunRequest,
    ),
  );
}
