/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type TriggerInvoiceCommsWebhookRequest = {
  /**
   * Invoice ID
   */
  id: string;
};

/** @internal */
export type TriggerInvoiceCommsWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const TriggerInvoiceCommsWebhookRequest$outboundSchema: z.ZodType<
  TriggerInvoiceCommsWebhookRequest$Outbound,
  z.ZodTypeDef,
  TriggerInvoiceCommsWebhookRequest
> = z.object({
  id: z.string(),
});

export function triggerInvoiceCommsWebhookRequestToJSON(
  triggerInvoiceCommsWebhookRequest: TriggerInvoiceCommsWebhookRequest,
): string {
  return JSON.stringify(
    TriggerInvoiceCommsWebhookRequest$outboundSchema.parse(
      triggerInvoiceCommsWebhookRequest,
    ),
  );
}
