/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TaxAssociationUpdateRequest,
  TaxAssociationUpdateRequest$Outbound,
  TaxAssociationUpdateRequest$outboundSchema,
} from "./taxassociationupdaterequest.js";

export type UpdateTaxAssociationRequest = {
  /**
   * Tax Config ID
   */
  id: string;
  /**
   * Tax Config Request
   */
  body: TaxAssociationUpdateRequest;
};

/** @internal */
export type UpdateTaxAssociationRequest$Outbound = {
  id: string;
  body: TaxAssociationUpdateRequest$Outbound;
};

/** @internal */
export const UpdateTaxAssociationRequest$outboundSchema: z.ZodType<
  UpdateTaxAssociationRequest$Outbound,
  z.ZodTypeDef,
  UpdateTaxAssociationRequest
> = z.object({
  id: z.string(),
  body: TaxAssociationUpdateRequest$outboundSchema,
});

export function updateTaxAssociationRequestToJSON(
  updateTaxAssociationRequest: UpdateTaxAssociationRequest,
): string {
  return JSON.stringify(
    UpdateTaxAssociationRequest$outboundSchema.parse(
      updateTaxAssociationRequest,
    ),
  );
}
