/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  UpdateFeatureRequest,
  UpdateFeatureRequest$Outbound,
  UpdateFeatureRequest$outboundSchema,
} from "./update-feature-request.js";

export type UpdateFeatureRequestRequest = {
  /**
   * Feature ID
   */
  id: string;
  /**
   * Feature update data
   */
  body: UpdateFeatureRequest;
};

/** @internal */
export type UpdateFeatureRequestRequest$Outbound = {
  id: string;
  body: UpdateFeatureRequest$Outbound;
};

/** @internal */
export const UpdateFeatureRequestRequest$outboundSchema: z.ZodMiniType<
  UpdateFeatureRequestRequest$Outbound,
  UpdateFeatureRequestRequest
> = z.object({
  id: z.string(),
  body: UpdateFeatureRequest$outboundSchema,
});

export function updateFeatureRequestRequestToJSON(
  updateFeatureRequestRequest: UpdateFeatureRequestRequest,
): string {
  return JSON.stringify(
    UpdateFeatureRequestRequest$outboundSchema.parse(
      updateFeatureRequestRequest,
    ),
  );
}
