/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  UpdateAlertSettingsRequest,
  UpdateAlertSettingsRequest$Outbound,
  UpdateAlertSettingsRequest$outboundSchema,
} from "./update-alert-settings-request.js";

export type UpdateAlertSettingsRequestRequest = {
  /**
   * Alert Settings ID
   */
  id: string;
  /**
   * Alert settings
   */
  body: UpdateAlertSettingsRequest;
};

/** @internal */
export type UpdateAlertSettingsRequestRequest$Outbound = {
  id: string;
  body: UpdateAlertSettingsRequest$Outbound;
};

/** @internal */
export const UpdateAlertSettingsRequestRequest$outboundSchema: z.ZodMiniType<
  UpdateAlertSettingsRequestRequest$Outbound,
  UpdateAlertSettingsRequestRequest
> = z.object({
  id: z.string(),
  body: UpdateAlertSettingsRequest$outboundSchema,
});

export function updateAlertSettingsRequestRequestToJSON(
  updateAlertSettingsRequestRequest: UpdateAlertSettingsRequestRequest,
): string {
  return JSON.stringify(
    UpdateAlertSettingsRequestRequest$outboundSchema.parse(
      updateAlertSettingsRequestRequest,
    ),
  );
}
