/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateServiceAccountRequest = {
  name: string;
};

/** @internal */
export type UpdateServiceAccountRequest$Outbound = {
  name: string;
};

/** @internal */
export const UpdateServiceAccountRequest$outboundSchema: z.ZodMiniType<
  UpdateServiceAccountRequest$Outbound,
  UpdateServiceAccountRequest
> = z.object({
  name: z.string(),
});

export function updateServiceAccountRequestToJSON(
  updateServiceAccountRequest: UpdateServiceAccountRequest,
): string {
  return JSON.stringify(
    UpdateServiceAccountRequest$outboundSchema.parse(
      updateServiceAccountRequest,
    ),
  );
}
