/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  EntitlementUsageResetPeriod,
  EntitlementUsageResetPeriod$outboundSchema,
} from "./entitlementusageresetperiod.js";

export type UpdateEntitlementRequest = {
  isEnabled?: boolean | undefined;
  isSoftLimit?: boolean | undefined;
  staticValue?: string | undefined;
  usageLimit?: number | undefined;
  usageResetPeriod?: EntitlementUsageResetPeriod | undefined;
};

/** @internal */
export type UpdateEntitlementRequest$Outbound = {
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  static_value?: string | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: string | undefined;
};

/** @internal */
export const UpdateEntitlementRequest$outboundSchema: z.ZodType<
  UpdateEntitlementRequest$Outbound,
  z.ZodTypeDef,
  UpdateEntitlementRequest
> = z.object({
  isEnabled: z.boolean().optional(),
  isSoftLimit: z.boolean().optional(),
  staticValue: z.string().optional(),
  usageLimit: z.number().int().optional(),
  usageResetPeriod: EntitlementUsageResetPeriod$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    isEnabled: "is_enabled",
    isSoftLimit: "is_soft_limit",
    staticValue: "static_value",
    usageLimit: "usage_limit",
    usageResetPeriod: "usage_reset_period",
  });
});

export function updateEntitlementRequestToJSON(
  updateEntitlementRequest: UpdateEntitlementRequest,
): string {
  return JSON.stringify(
    UpdateEntitlementRequest$outboundSchema.parse(updateEntitlementRequest),
  );
}
