/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateCostsheetRequest = {
  description?: string | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export type UpdateCostsheetRequest$Outbound = {
  description?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export const UpdateCostsheetRequest$outboundSchema: z.ZodType<
  UpdateCostsheetRequest$Outbound,
  z.ZodTypeDef,
  UpdateCostsheetRequest
> = z.object({
  description: z.string().optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    lookupKey: "lookup_key",
  });
});

export function updateCostsheetRequestToJSON(
  updateCostsheetRequest: UpdateCostsheetRequest,
): string {
  return JSON.stringify(
    UpdateCostsheetRequest$outboundSchema.parse(updateCostsheetRequest),
  );
}
