/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  PaymentStatus,
  PaymentStatus$outboundSchema,
} from "./payment-status.js";

export type UpdatePaymentStatusRequest = {
  /**
   * amount is the optional payment amount to record
   */
  amount?: string | undefined;
  paymentStatus: PaymentStatus;
};

/** @internal */
export type UpdatePaymentStatusRequest$Outbound = {
  amount?: string | undefined;
  payment_status: string;
};

/** @internal */
export const UpdatePaymentStatusRequest$outboundSchema: z.ZodMiniType<
  UpdatePaymentStatusRequest$Outbound,
  UpdatePaymentStatusRequest
> = z.pipe(
  z.object({
    amount: z.optional(z.string()),
    paymentStatus: PaymentStatus$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      paymentStatus: "payment_status",
    });
  }),
);

export function updatePaymentStatusRequestToJSON(
  updatePaymentStatusRequest: UpdatePaymentStatusRequest,
): string {
  return JSON.stringify(
    UpdatePaymentStatusRequest$outboundSchema.parse(updatePaymentStatusRequest),
  );
}
