/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdatePaymentRequest = {
  errorMessage?: string | undefined;
  failedAt?: Date | undefined;
  gatewayPaymentId?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  paymentGateway?: string | undefined;
  paymentMethodId?: string | undefined;
  paymentStatus?: string | undefined;
  succeededAt?: Date | undefined;
};

/** @internal */
export type UpdatePaymentRequest$Outbound = {
  error_message?: string | undefined;
  failed_at?: string | undefined;
  gateway_payment_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_gateway?: string | undefined;
  payment_method_id?: string | undefined;
  payment_status?: string | undefined;
  succeeded_at?: string | undefined;
};

/** @internal */
export const UpdatePaymentRequest$outboundSchema: z.ZodMiniType<
  UpdatePaymentRequest$Outbound,
  UpdatePaymentRequest
> = z.pipe(
  z.object({
    errorMessage: z.optional(z.string()),
    failedAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    gatewayPaymentId: z.optional(z.string()),
    metadata: z.optional(z.record(z.string(), z.string())),
    paymentGateway: z.optional(z.string()),
    paymentMethodId: z.optional(z.string()),
    paymentStatus: z.optional(z.string()),
    succeededAt: z.optional(
      z.pipe(z.date(), z.transform(v => v.toISOString())),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      errorMessage: "error_message",
      failedAt: "failed_at",
      gatewayPaymentId: "gateway_payment_id",
      paymentGateway: "payment_gateway",
      paymentMethodId: "payment_method_id",
      paymentStatus: "payment_status",
      succeededAt: "succeeded_at",
    });
  }),
);

export function updatePaymentRequestToJSON(
  updatePaymentRequest: UpdatePaymentRequest,
): string {
  return JSON.stringify(
    UpdatePaymentRequest$outboundSchema.parse(updatePaymentRequest),
  );
}
