/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  UpdateWalletRequest,
  UpdateWalletRequest$Outbound,
  UpdateWalletRequest$outboundSchema,
} from "./update-wallet-request.js";

export type UpdateWalletRequestRequest = {
  /**
   * Wallet ID
   */
  id: string;
  /**
   * Update wallet request
   */
  body: UpdateWalletRequest;
};

/** @internal */
export type UpdateWalletRequestRequest$Outbound = {
  id: string;
  body: UpdateWalletRequest$Outbound;
};

/** @internal */
export const UpdateWalletRequestRequest$outboundSchema: z.ZodMiniType<
  UpdateWalletRequestRequest$Outbound,
  UpdateWalletRequestRequest
> = z.object({
  id: z.string(),
  body: UpdateWalletRequest$outboundSchema,
});

export function updateWalletRequestRequestToJSON(
  updateWalletRequestRequest: UpdateWalletRequestRequest,
): string {
  return JSON.stringify(
    UpdateWalletRequestRequest$outboundSchema.parse(updateWalletRequestRequest),
  );
}
