/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  UpdateScheduledTaskRequest,
  UpdateScheduledTaskRequest$Outbound,
  UpdateScheduledTaskRequest$outboundSchema,
} from "./update-scheduled-task-request.js";

export type UpdateScheduledTaskRequestRequest = {
  /**
   * Scheduled Task ID
   */
  id: string;
  /**
   * Update request (enabled: true/false to pause/resume)
   */
  body: UpdateScheduledTaskRequest;
};

/** @internal */
export type UpdateScheduledTaskRequestRequest$Outbound = {
  id: string;
  body: UpdateScheduledTaskRequest$Outbound;
};

/** @internal */
export const UpdateScheduledTaskRequestRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduledTaskRequestRequest$Outbound,
  UpdateScheduledTaskRequestRequest
> = z.object({
  id: z.string(),
  body: UpdateScheduledTaskRequest$outboundSchema,
});

export function updateScheduledTaskRequestRequestToJSON(
  updateScheduledTaskRequestRequest: UpdateScheduledTaskRequestRequest,
): string {
  return JSON.stringify(
    UpdateScheduledTaskRequestRequest$outboundSchema.parse(
      updateScheduledTaskRequestRequest,
    ),
  );
}
