/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdatePlanRequest = {
  description?: string | undefined;
  displayOrder?: number | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export type UpdatePlanRequest$Outbound = {
  description?: string | undefined;
  display_order?: number | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export const UpdatePlanRequest$outboundSchema: z.ZodType<
  UpdatePlanRequest$Outbound,
  z.ZodTypeDef,
  UpdatePlanRequest
> = z.object({
  description: z.string().optional(),
  displayOrder: z.number().int().optional(),
  lookupKey: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    displayOrder: "display_order",
    lookupKey: "lookup_key",
  });
});

export function updatePlanRequestToJSON(
  updatePlanRequest: UpdatePlanRequest,
): string {
  return JSON.stringify(
    UpdatePlanRequest$outboundSchema.parse(updatePlanRequest),
  );
}
