/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  UpdatePriceRequest,
  UpdatePriceRequest$Outbound,
  UpdatePriceRequest$outboundSchema,
} from "./updatepricerequest.js";

export type UpdatePriceRequestRequest = {
  /**
   * Price ID
   */
  id: string;
  /**
   * Price configuration
   */
  body: UpdatePriceRequest;
};

/** @internal */
export type UpdatePriceRequestRequest$Outbound = {
  id: string;
  body: UpdatePriceRequest$Outbound;
};

/** @internal */
export const UpdatePriceRequestRequest$outboundSchema: z.ZodType<
  UpdatePriceRequestRequest$Outbound,
  z.ZodTypeDef,
  UpdatePriceRequestRequest
> = z.object({
  id: z.string(),
  body: UpdatePriceRequest$outboundSchema,
});

export function updatePriceRequestRequestToJSON(
  updatePriceRequestRequest: UpdatePriceRequestRequest,
): string {
  return JSON.stringify(
    UpdatePriceRequestRequest$outboundSchema.parse(updatePriceRequestRequest),
  );
}
