/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  CostsheetResponse,
  CostsheetResponse$inboundSchema,
} from "./costsheet-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type UpdateCostsheetResponse = {
  costsheet?: CostsheetResponse | undefined;
};

/** @internal */
export const UpdateCostsheetResponse$inboundSchema: z.ZodMiniType<
  UpdateCostsheetResponse,
  unknown
> = z.object({
  costsheet: types.optional(CostsheetResponse$inboundSchema),
});

export function updateCostsheetResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCostsheetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCostsheetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCostsheetResponse' from JSON`,
  );
}
