/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdateScheduledTaskRequest = {
  enabled: boolean;
};

/** @internal */
export type UpdateScheduledTaskRequest$Outbound = {
  enabled: boolean;
};

/** @internal */
export const UpdateScheduledTaskRequest$outboundSchema: z.ZodMiniType<
  UpdateScheduledTaskRequest$Outbound,
  UpdateScheduledTaskRequest
> = z.object({
  enabled: z.boolean(),
});

export function updateScheduledTaskRequestToJSON(
  updateScheduledTaskRequest: UpdateScheduledTaskRequest,
): string {
  return JSON.stringify(
    UpdateScheduledTaskRequest$outboundSchema.parse(updateScheduledTaskRequest),
  );
}
