/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  TenantBillingDetails,
  TenantBillingDetails$Outbound,
  TenantBillingDetails$outboundSchema,
} from "./tenantbillingdetails.js";

export type UpdateTenantRequest = {
  billingDetails?: TenantBillingDetails | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export type UpdateTenantRequest$Outbound = {
  billing_details?: TenantBillingDetails$Outbound | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

/** @internal */
export const UpdateTenantRequest$outboundSchema: z.ZodType<
  UpdateTenantRequest$Outbound,
  z.ZodTypeDef,
  UpdateTenantRequest
> = z.object({
  billingDetails: TenantBillingDetails$outboundSchema.optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    billingDetails: "billing_details",
  });
});

export function updateTenantRequestToJSON(
  updateTenantRequest: UpdateTenantRequest,
): string {
  return JSON.stringify(
    UpdateTenantRequest$outboundSchema.parse(updateTenantRequest),
  );
}
