/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  AnalyticsViewDefinition,
  AnalyticsViewDefinition$inboundSchema,
} from "./analytics-view-definition.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ViewResponse = {
  definition?: AnalyticsViewDefinition | undefined;
  id?: string | undefined;
  name?: string | undefined;
  version?: number | undefined;
};

/** @internal */
export const ViewResponse$inboundSchema: z.ZodMiniType<ViewResponse, unknown> =
  z.object({
    definition: types.optional(AnalyticsViewDefinition$inboundSchema),
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    version: types.optional(types.number()),
  });

export function viewResponseFromJSON(
  jsonString: string,
): SafeParseResult<ViewResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ViewResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ViewResponse' from JSON`,
  );
}
