/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const WalletStatus = {
  Active: "active",
  Frozen: "frozen",
  Closed: "closed",
} as const;
export type WalletStatus = OpenEnum<typeof WalletStatus>;

/** @internal */
export const WalletStatus$inboundSchema: z.ZodType<
  WalletStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(WalletStatus);
/** @internal */
export const WalletStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  WalletStatus
> = openEnums.outboundSchema(WalletStatus);
