/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const WalletType = {
  PrePaid: "PRE_PAID",
  PostPaid: "POST_PAID",
} as const;
export type WalletType = OpenEnum<typeof WalletType>;

/** @internal */
export const WalletType$inboundSchema: z.ZodMiniType<WalletType, unknown> =
  openEnums.inboundSchema(WalletType);
/** @internal */
export const WalletType$outboundSchema: z.ZodMiniType<string, WalletType> =
  openEnums.outboundSchema(WalletType);
