/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  InvoiceResponse,
  InvoiceResponse$inboundSchema,
} from "./invoiceresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhookeventname.js";

export type WebhookDtoInvoiceWebhookPayload = {
  eventType?: WebhookEventName | undefined;
  invoice?: InvoiceResponse | undefined;
};

/** @internal */
export const WebhookDtoInvoiceWebhookPayload$inboundSchema: z.ZodType<
  WebhookDtoInvoiceWebhookPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  event_type: types.optional(WebhookEventName$inboundSchema),
  invoice: types.optional(InvoiceResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "event_type": "eventType",
  });
});

export function webhookDtoInvoiceWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoInvoiceWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoInvoiceWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoInvoiceWebhookPayload' from JSON`,
  );
}
