/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  CustomerResponse,
  CustomerResponse$inboundSchema,
} from "./customerresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhookeventname.js";

export type WebhookDtoCustomerWebhookPayload = {
  /**
   * Customer response object containing all customer information
   */
  customer?: CustomerResponse | undefined;
  eventType?: WebhookEventName | undefined;
};

/** @internal */
export const WebhookDtoCustomerWebhookPayload$inboundSchema: z.ZodType<
  WebhookDtoCustomerWebhookPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer: types.optional(CustomerResponse$inboundSchema),
  event_type: types.optional(WebhookEventName$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "event_type": "eventType",
  });
});

export function webhookDtoCustomerWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoCustomerWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoCustomerWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoCustomerWebhookPayload' from JSON`,
  );
}
