/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  CustomerResponse,
  CustomerResponse$inboundSchema,
} from "./customer-response.js";
import {
  FeatureResponse,
  FeatureResponse$inboundSchema,
} from "./feature-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  WalletResponse,
  WalletResponse$inboundSchema,
} from "./wallet-response.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhook-event-name.js";

export type WebhookDtoAlertWebhookPayload = {
  alertStatus?: string | undefined;
  alertType?: string | undefined;
  /**
   * Customer response object containing all customer information
   */
  customer?: CustomerResponse | undefined;
  eventType?: WebhookEventName | undefined;
  feature?: FeatureResponse | undefined;
  wallet?: WalletResponse | undefined;
};

/** @internal */
export const WebhookDtoAlertWebhookPayload$inboundSchema: z.ZodMiniType<
  WebhookDtoAlertWebhookPayload,
  unknown
> = z.pipe(
  z.object({
    alert_status: types.optional(types.string()),
    alert_type: types.optional(types.string()),
    customer: types.optional(CustomerResponse$inboundSchema),
    event_type: types.optional(WebhookEventName$inboundSchema),
    feature: types.optional(FeatureResponse$inboundSchema),
    wallet: types.optional(WalletResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "alert_status": "alertStatus",
      "alert_type": "alertType",
      "event_type": "eventType",
    });
  }),
);

export function webhookDtoAlertWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoAlertWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoAlertWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoAlertWebhookPayload' from JSON`,
  );
}
