/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  MeterAggregation,
  MeterAggregation$inboundSchema,
} from "./meter-aggregation.js";
import { ResetUsage, ResetUsage$inboundSchema } from "./reset-usage.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type WebhookDtoMeter = {
  aggregation?: MeterAggregation | undefined;
  eventName?: string | undefined;
  id?: string | undefined;
  name?: string | undefined;
  resetUsage?: ResetUsage | undefined;
};

/** @internal */
export const WebhookDtoMeter$inboundSchema: z.ZodMiniType<
  WebhookDtoMeter,
  unknown
> = z.pipe(
  z.object({
    aggregation: types.optional(MeterAggregation$inboundSchema),
    event_name: types.optional(types.string()),
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    reset_usage: types.optional(ResetUsage$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_name": "eventName",
      "reset_usage": "resetUsage",
    });
  }),
);

export function webhookDtoMeterFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoMeter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoMeter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoMeter' from JSON`,
  );
}
