/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  BillingCadence,
  BillingCadence$inboundSchema,
} from "./billing-cadence.js";
import { BillingModel, BillingModel$inboundSchema } from "./billing-model.js";
import {
  BillingPeriod,
  BillingPeriod$inboundSchema,
} from "./billing-period.js";
import { BillingTier, BillingTier$inboundSchema } from "./billing-tier.js";
import {
  InvoiceCadence,
  InvoiceCadence$inboundSchema,
} from "./invoice-cadence.js";
import {
  PriceJSONBTransformQuantity,
  PriceJSONBTransformQuantity$inboundSchema,
} from "./price-jsonb-transform-quantity.js";
import {
  PricePriceTier,
  PricePriceTier$inboundSchema,
} from "./price-price-tier.js";
import { PriceType, PriceType$inboundSchema } from "./price-type.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  WebhookDtoMeter,
  WebhookDtoMeter$inboundSchema,
} from "./webhook-dto-meter.js";

export type WebhookDtoPrice = {
  amount?: string | undefined;
  billingCadence?: BillingCadence | undefined;
  billingModel?: BillingModel | undefined;
  billingPeriod?: BillingPeriod | undefined;
  billingPeriodCount?: number | undefined;
  currency?: string | undefined;
  description?: string | undefined;
  displayAmount?: string | undefined;
  displayName?: string | undefined;
  displayPriceUnitAmount?: string | undefined;
  id?: string | undefined;
  invoiceCadence?: InvoiceCadence | undefined;
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: WebhookDtoMeter | undefined;
  meterId?: string | undefined;
  priceUnit?: string | undefined;
  priceUnitAmount?: string | undefined;
  tierMode?: BillingTier | undefined;
  tiers?: Array<PricePriceTier> | undefined;
  transformQuantity?: PriceJSONBTransformQuantity | undefined;
  type?: PriceType | undefined;
};

/** @internal */
export const WebhookDtoPrice$inboundSchema: z.ZodMiniType<
  WebhookDtoPrice,
  unknown
> = z.pipe(
  z.object({
    amount: types.optional(types.string()),
    billing_cadence: types.optional(BillingCadence$inboundSchema),
    billing_model: types.optional(BillingModel$inboundSchema),
    billing_period: types.optional(BillingPeriod$inboundSchema),
    billing_period_count: types.optional(types.number()),
    currency: types.optional(types.string()),
    description: types.optional(types.string()),
    display_amount: types.optional(types.string()),
    display_name: types.optional(types.string()),
    display_price_unit_amount: types.optional(types.string()),
    id: types.optional(types.string()),
    invoice_cadence: types.optional(InvoiceCadence$inboundSchema),
    lookup_key: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), types.string())),
    meter: types.optional(WebhookDtoMeter$inboundSchema),
    meter_id: types.optional(types.string()),
    price_unit: types.optional(types.string()),
    price_unit_amount: types.optional(types.string()),
    tier_mode: types.optional(BillingTier$inboundSchema),
    tiers: types.optional(z.array(PricePriceTier$inboundSchema)),
    transform_quantity: types.optional(
      PriceJSONBTransformQuantity$inboundSchema,
    ),
    type: types.optional(PriceType$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "billing_cadence": "billingCadence",
      "billing_model": "billingModel",
      "billing_period": "billingPeriod",
      "billing_period_count": "billingPeriodCount",
      "display_amount": "displayAmount",
      "display_name": "displayName",
      "display_price_unit_amount": "displayPriceUnitAmount",
      "invoice_cadence": "invoiceCadence",
      "lookup_key": "lookupKey",
      "meter_id": "meterId",
      "price_unit": "priceUnit",
      "price_unit_amount": "priceUnitAmount",
      "tier_mode": "tierMode",
      "transform_quantity": "transformQuantity",
    });
  }),
);

export function webhookDtoPriceFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoPrice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoPrice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoPrice' from JSON`,
  );
}
