/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  InvoiceResponse,
  InvoiceResponse$inboundSchema,
} from "./invoice-response.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhook-event-name.js";

export type WebhookDtoCommunicationWebhookPayload = {
  eventType?: WebhookEventName | undefined;
  invoice?: InvoiceResponse | undefined;
};

/** @internal */
export const WebhookDtoCommunicationWebhookPayload$inboundSchema: z.ZodMiniType<
  WebhookDtoCommunicationWebhookPayload,
  unknown
> = z.pipe(
  z.object({
    event_type: types.optional(WebhookEventName$inboundSchema),
    invoice: types.optional(InvoiceResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
    });
  }),
);

export function webhookDtoCommunicationWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoCommunicationWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookDtoCommunicationWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoCommunicationWebhookPayload' from JSON`,
  );
}
