/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  PaymentResponse,
  PaymentResponse$inboundSchema,
} from "./paymentresponse.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhookeventname.js";

export type WebhookDtoPaymentWebhookPayload = {
  eventType?: WebhookEventName | undefined;
  payment?: PaymentResponse | undefined;
};

/** @internal */
export const WebhookDtoPaymentWebhookPayload$inboundSchema: z.ZodType<
  WebhookDtoPaymentWebhookPayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  event_type: types.optional(WebhookEventName$inboundSchema),
  payment: types.optional(PaymentResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "event_type": "eventType",
  });
});

export function webhookDtoPaymentWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoPaymentWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoPaymentWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoPaymentWebhookPayload' from JSON`,
  );
}
