/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import {
  RejectedEventReason,
  RejectedEventReason$inboundSchema,
} from "./rejected-event-reason.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  WebhookDtoRejectedEventData,
  WebhookDtoRejectedEventData$inboundSchema,
} from "./webhook-dto-rejected-event-data.js";
import {
  WebhookEventName,
  WebhookEventName$inboundSchema,
} from "./webhook-event-name.js";

export type WebhookDtoRejectedEventWebhookPayload = {
  event?: WebhookDtoRejectedEventData | undefined;
  eventType?: WebhookEventName | undefined;
  reason?: RejectedEventReason | undefined;
};

/** @internal */
export const WebhookDtoRejectedEventWebhookPayload$inboundSchema: z.ZodMiniType<
  WebhookDtoRejectedEventWebhookPayload,
  unknown
> = z.pipe(
  z.object({
    event: types.optional(WebhookDtoRejectedEventData$inboundSchema),
    event_type: types.optional(WebhookEventName$inboundSchema),
    reason: types.optional(RejectedEventReason$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
    });
  }),
);

export function webhookDtoRejectedEventWebhookPayloadFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoRejectedEventWebhookPayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookDtoRejectedEventWebhookPayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoRejectedEventWebhookPayload' from JSON`,
  );
}
