/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { CouponType, CouponType$inboundSchema } from "./coupon-type.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type WebhookDtoCouponApplication = {
  appliedAt?: Date | undefined;
  couponAssociationId?: string | undefined;
  couponId?: string | undefined;
  couponSnapshot?: { [k: string]: any } | undefined;
  currency?: string | undefined;
  discountPercentage?: string | undefined;
  discountType?: CouponType | undefined;
  discountedAmount?: string | undefined;
  finalPrice?: string | undefined;
  id?: string | undefined;
  invoiceLineItemId?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  originalPrice?: string | undefined;
  subscriptionId?: string | undefined;
};

/** @internal */
export const WebhookDtoCouponApplication$inboundSchema: z.ZodMiniType<
  WebhookDtoCouponApplication,
  unknown
> = z.pipe(
  z.object({
    applied_at: types.optional(types.date()),
    coupon_association_id: types.optional(types.string()),
    coupon_id: types.optional(types.string()),
    coupon_snapshot: types.optional(z.record(z.string(), z.any())),
    currency: types.optional(types.string()),
    discount_percentage: types.optional(types.string()),
    discount_type: types.optional(CouponType$inboundSchema),
    discounted_amount: types.optional(types.string()),
    final_price: types.optional(types.string()),
    id: types.optional(types.string()),
    invoice_line_item_id: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), types.string())),
    original_price: types.optional(types.string()),
    subscription_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "applied_at": "appliedAt",
      "coupon_association_id": "couponAssociationId",
      "coupon_id": "couponId",
      "coupon_snapshot": "couponSnapshot",
      "discount_percentage": "discountPercentage",
      "discount_type": "discountType",
      "discounted_amount": "discountedAmount",
      "final_price": "finalPrice",
      "invoice_line_item_id": "invoiceLineItemId",
      "original_price": "originalPrice",
      "subscription_id": "subscriptionId",
    });
  }),
);

export function webhookDtoCouponApplicationFromJSON(
  jsonString: string,
): SafeParseResult<WebhookDtoCouponApplication, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookDtoCouponApplication$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookDtoCouponApplication' from JSON`,
  );
}
