/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { checkoutCreateCheckoutSession } from "../funcs/checkout-create-checkout-session.js";
import { checkoutDeleteCheckoutSession } from "../funcs/checkout-delete-checkout-session.js";
import { checkoutGetCheckoutSession } from "../funcs/checkout-get-checkout-session.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class Checkout extends ClientSDK {
  /**
   * Create checkout session
   */
  async createCheckoutSession(
    request: models.CreateCheckoutSessionRequest,
    options?: RequestOptions,
  ): Promise<models.CheckoutSessionResponse> {
    return unwrapAsync(checkoutCreateCheckoutSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Get checkout session
   */
  async getCheckoutSession(
    id: string,
    options?: RequestOptions,
  ): Promise<models.CheckoutSessionResponse> {
    return unwrapAsync(checkoutGetCheckoutSession(
      this,
      id,
      options,
    ));
  }

  /**
   * Delete checkout session
   */
  async deleteCheckoutSession(
    id: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(checkoutDeleteCheckoutSession(
      this,
      id,
      options,
    ));
  }
}
