/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { costsCreateCostsheet } from "../funcs/costsCreateCostsheet.js";
import { costsDeleteCostsheet } from "../funcs/costsDeleteCostsheet.js";
import { costsGetActiveCostsheet } from "../funcs/costsGetActiveCostsheet.js";
import { costsGetCostsheet } from "../funcs/costsGetCostsheet.js";
import { costsGetDetailedCostAnalytics } from "../funcs/costsGetDetailedCostAnalytics.js";
import { costsGetDetailedCostAnalyticsV2 } from "../funcs/costsGetDetailedCostAnalyticsV2.js";
import { costsQueryCostsheet } from "../funcs/costsQueryCostsheet.js";
import { costsUpdateCostsheet } from "../funcs/costsUpdateCostsheet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class Costs extends ClientSDK {
  /**
   * Create costsheet
   *
   * @remarks
   * Use when setting up a new pricing configuration (e.g. a new product or region). Costsheets group prices and define the default for the environment.
   */
  async createCostsheet(
    request: models.CreateCostsheetRequest,
    options?: RequestOptions,
  ): Promise<models.CreateCostsheetResponse> {
    return unwrapAsync(costsCreateCostsheet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete costsheet
   *
   * @remarks
   * Use when retiring a costsheet (e.g. end-of-life product). Soft-deletes; status set to deleted.
   */
  async deleteCostsheet(
    id: string,
    options?: RequestOptions,
  ): Promise<models.DeleteCostsheetResponse> {
    return unwrapAsync(costsDeleteCostsheet(
      this,
      id,
      options,
    ));
  }

  /**
   * Get active costsheet
   *
   * @remarks
   * Use when you need the tenant's default pricing configuration (e.g. for checkout or plan display). Returns the active costsheet for the environment.
   */
  async getActiveCostsheet(
    options?: RequestOptions,
  ): Promise<models.CostsheetResponse> {
    return unwrapAsync(costsGetActiveCostsheet(
      this,
      options,
    ));
  }

  /**
   * Get costsheet
   *
   * @remarks
   * Use when you need to load a single costsheet (e.g. for editing or display). Supports optional expand for related prices.
   */
  async getCostsheet(
    id: string,
    expand?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.GetCostsheetResponse> {
    return unwrapAsync(costsGetCostsheet(
      this,
      id,
      expand,
      options,
    ));
  }

  /**
   * Get combined revenue and cost analytics
   *
   * @remarks
   * Use when building dashboards or reports that need revenue vs cost, ROI, and margin over a time period (e.g. finance views or executive summaries).
   */
  async getDetailedCostAnalytics(
    request: models.GetCostAnalyticsRequest,
    options?: RequestOptions,
  ): Promise<models.GetDetailedCostAnalyticsResponse> {
    return unwrapAsync(costsGetDetailedCostAnalytics(
      this,
      request,
      options,
    ));
  }

  /**
   * Get combined revenue and cost analytics (V2)
   *
   * @remarks
   * Use when you need the same revenue/cost/ROI analytics but computed from the costsheet usage-tracking pipeline (e.g. for consistency with usage-based cost data).
   */
  async getDetailedCostAnalyticsV2(
    request: models.GetCostAnalyticsRequest,
    options?: RequestOptions,
  ): Promise<models.GetDetailedCostAnalyticsResponse> {
    return unwrapAsync(costsGetDetailedCostAnalyticsV2(
      this,
      request,
      options,
    ));
  }

  /**
   * Query costsheets
   *
   * @remarks
   * Use when listing or searching costsheets (e.g. admin catalog). Returns a paginated list; supports filtering and sorting.
   */
  async queryCostsheet(
    request: models.CostsheetFilter,
    options?: RequestOptions,
  ): Promise<models.ListCostsheetResponse> {
    return unwrapAsync(costsQueryCostsheet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update costsheet
   *
   * @remarks
   * Use when changing costsheet name or metadata.
   */
  async updateCostsheet(
    id: string,
    body: models.UpdateCostsheetRequest,
    options?: RequestOptions,
  ): Promise<models.UpdateCostsheetResponse> {
    return unwrapAsync(costsUpdateCostsheet(
      this,
      id,
      body,
      options,
    ));
  }
}
