/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhookEventsPostWebhookEventsCreditNoteCreated } from "../funcs/webhookEventsPostWebhookEventsCreditNoteCreated.js";
import { webhookEventsPostWebhookEventsCreditNoteUpdated } from "../funcs/webhookEventsPostWebhookEventsCreditNoteUpdated.js";
import { webhookEventsPostWebhookEventsCustomerCreated } from "../funcs/webhookEventsPostWebhookEventsCustomerCreated.js";
import { webhookEventsPostWebhookEventsCustomerDeleted } from "../funcs/webhookEventsPostWebhookEventsCustomerDeleted.js";
import { webhookEventsPostWebhookEventsCustomerUpdated } from "../funcs/webhookEventsPostWebhookEventsCustomerUpdated.js";
import { webhookEventsPostWebhookEventsEntitlementCreated } from "../funcs/webhookEventsPostWebhookEventsEntitlementCreated.js";
import { webhookEventsPostWebhookEventsEntitlementDeleted } from "../funcs/webhookEventsPostWebhookEventsEntitlementDeleted.js";
import { webhookEventsPostWebhookEventsEntitlementUpdated } from "../funcs/webhookEventsPostWebhookEventsEntitlementUpdated.js";
import { webhookEventsPostWebhookEventsFeatureCreated } from "../funcs/webhookEventsPostWebhookEventsFeatureCreated.js";
import { webhookEventsPostWebhookEventsFeatureDeleted } from "../funcs/webhookEventsPostWebhookEventsFeatureDeleted.js";
import { webhookEventsPostWebhookEventsFeatureUpdated } from "../funcs/webhookEventsPostWebhookEventsFeatureUpdated.js";
import { webhookEventsPostWebhookEventsFeatureWalletBalanceAlert } from "../funcs/webhookEventsPostWebhookEventsFeatureWalletBalanceAlert.js";
import { webhookEventsPostWebhookEventsInvoiceCommunicationTriggered } from "../funcs/webhookEventsPostWebhookEventsInvoiceCommunicationTriggered.js";
import { webhookEventsPostWebhookEventsInvoicePaymentOverdue } from "../funcs/webhookEventsPostWebhookEventsInvoicePaymentOverdue.js";
import { webhookEventsPostWebhookEventsInvoiceUpdate } from "../funcs/webhookEventsPostWebhookEventsInvoiceUpdate.js";
import { webhookEventsPostWebhookEventsInvoiceUpdateFinalized } from "../funcs/webhookEventsPostWebhookEventsInvoiceUpdateFinalized.js";
import { webhookEventsPostWebhookEventsInvoiceUpdatePayment } from "../funcs/webhookEventsPostWebhookEventsInvoiceUpdatePayment.js";
import { webhookEventsPostWebhookEventsInvoiceUpdateVoided } from "../funcs/webhookEventsPostWebhookEventsInvoiceUpdateVoided.js";
import { webhookEventsPostWebhookEventsPaymentCreated } from "../funcs/webhookEventsPostWebhookEventsPaymentCreated.js";
import { webhookEventsPostWebhookEventsPaymentFailed } from "../funcs/webhookEventsPostWebhookEventsPaymentFailed.js";
import { webhookEventsPostWebhookEventsPaymentPending } from "../funcs/webhookEventsPostWebhookEventsPaymentPending.js";
import { webhookEventsPostWebhookEventsPaymentSuccess } from "../funcs/webhookEventsPostWebhookEventsPaymentSuccess.js";
import { webhookEventsPostWebhookEventsPaymentUpdated } from "../funcs/webhookEventsPostWebhookEventsPaymentUpdated.js";
import { webhookEventsPostWebhookEventsSubscriptionActivated } from "../funcs/webhookEventsPostWebhookEventsSubscriptionActivated.js";
import { webhookEventsPostWebhookEventsSubscriptionCancelled } from "../funcs/webhookEventsPostWebhookEventsSubscriptionCancelled.js";
import { webhookEventsPostWebhookEventsSubscriptionCreated } from "../funcs/webhookEventsPostWebhookEventsSubscriptionCreated.js";
import { webhookEventsPostWebhookEventsSubscriptionDraftCreated } from "../funcs/webhookEventsPostWebhookEventsSubscriptionDraftCreated.js";
import { webhookEventsPostWebhookEventsSubscriptionPaused } from "../funcs/webhookEventsPostWebhookEventsSubscriptionPaused.js";
import { webhookEventsPostWebhookEventsSubscriptionPhaseCreated } from "../funcs/webhookEventsPostWebhookEventsSubscriptionPhaseCreated.js";
import { webhookEventsPostWebhookEventsSubscriptionPhaseDeleted } from "../funcs/webhookEventsPostWebhookEventsSubscriptionPhaseDeleted.js";
import { webhookEventsPostWebhookEventsSubscriptionPhaseUpdated } from "../funcs/webhookEventsPostWebhookEventsSubscriptionPhaseUpdated.js";
import { webhookEventsPostWebhookEventsSubscriptionRenewalDue } from "../funcs/webhookEventsPostWebhookEventsSubscriptionRenewalDue.js";
import { webhookEventsPostWebhookEventsSubscriptionResumed } from "../funcs/webhookEventsPostWebhookEventsSubscriptionResumed.js";
import { webhookEventsPostWebhookEventsSubscriptionUpdated } from "../funcs/webhookEventsPostWebhookEventsSubscriptionUpdated.js";
import { webhookEventsPostWebhookEventsWalletCreated } from "../funcs/webhookEventsPostWebhookEventsWalletCreated.js";
import { webhookEventsPostWebhookEventsWalletCreditBalanceDropped } from "../funcs/webhookEventsPostWebhookEventsWalletCreditBalanceDropped.js";
import { webhookEventsPostWebhookEventsWalletCreditBalanceRecovered } from "../funcs/webhookEventsPostWebhookEventsWalletCreditBalanceRecovered.js";
import { webhookEventsPostWebhookEventsWalletOngoingBalanceDropped } from "../funcs/webhookEventsPostWebhookEventsWalletOngoingBalanceDropped.js";
import { webhookEventsPostWebhookEventsWalletOngoingBalanceRecovered } from "../funcs/webhookEventsPostWebhookEventsWalletOngoingBalanceRecovered.js";
import { webhookEventsPostWebhookEventsWalletTerminated } from "../funcs/webhookEventsPostWebhookEventsWalletTerminated.js";
import { webhookEventsPostWebhookEventsWalletTransactionCreated } from "../funcs/webhookEventsPostWebhookEventsWalletTransactionCreated.js";
import { webhookEventsPostWebhookEventsWalletUpdated } from "../funcs/webhookEventsPostWebhookEventsWalletUpdated.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import * as models from "./models/index.js";

export class WebhookEvents extends ClientSDK {
  /**
   * credit_note.created
   *
   * @remarks
   * Fired when a new credit note is created. Doc-only for parsing.
   */
  async postWebhookEventsCreditNoteCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoCreditNoteWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsCreditNoteCreated(
      this,
      options,
    ));
  }

  /**
   * credit_note.updated
   *
   * @remarks
   * Fired when a credit note is updated. Doc-only for parsing.
   */
  async postWebhookEventsCreditNoteUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoCreditNoteWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsCreditNoteUpdated(
      this,
      options,
    ));
  }

  /**
   * customer.created
   *
   * @remarks
   * Fired when a new customer is created. Doc-only for parsing.
   */
  async postWebhookEventsCustomerCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoCustomerWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsCustomerCreated(
      this,
      options,
    ));
  }

  /**
   * customer.deleted
   *
   * @remarks
   * Fired when a customer is deleted. Doc-only for parsing.
   */
  async postWebhookEventsCustomerDeleted(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoCustomerWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsCustomerDeleted(
      this,
      options,
    ));
  }

  /**
   * customer.updated
   *
   * @remarks
   * Fired when a customer is updated. Doc-only for parsing.
   */
  async postWebhookEventsCustomerUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoCustomerWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsCustomerUpdated(
      this,
      options,
    ));
  }

  /**
   * entitlement.created
   *
   * @remarks
   * Fired when a new entitlement is created. Doc-only for parsing.
   */
  async postWebhookEventsEntitlementCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoEntitlementWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsEntitlementCreated(
      this,
      options,
    ));
  }

  /**
   * entitlement.deleted
   *
   * @remarks
   * Fired when an entitlement is deleted. Doc-only for parsing.
   */
  async postWebhookEventsEntitlementDeleted(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoEntitlementWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsEntitlementDeleted(
      this,
      options,
    ));
  }

  /**
   * entitlement.updated
   *
   * @remarks
   * Fired when an entitlement is updated. Doc-only for parsing.
   */
  async postWebhookEventsEntitlementUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoEntitlementWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsEntitlementUpdated(
      this,
      options,
    ));
  }

  /**
   * feature.created
   *
   * @remarks
   * Fired when a new feature is created. Doc-only for parsing.
   */
  async postWebhookEventsFeatureCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoFeatureWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsFeatureCreated(
      this,
      options,
    ));
  }

  /**
   * feature.deleted
   *
   * @remarks
   * Fired when a feature is deleted. Doc-only for parsing.
   */
  async postWebhookEventsFeatureDeleted(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoFeatureWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsFeatureDeleted(
      this,
      options,
    ));
  }

  /**
   * feature.updated
   *
   * @remarks
   * Fired when a feature is updated. Doc-only for parsing.
   */
  async postWebhookEventsFeatureUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoFeatureWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsFeatureUpdated(
      this,
      options,
    ));
  }

  /**
   * feature.wallet_balance.alert
   *
   * @remarks
   * Fired when a feature's associated wallet balance crosses an alert threshold. Doc-only for parsing.
   */
  async postWebhookEventsFeatureWalletBalanceAlert(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoAlertWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsFeatureWalletBalanceAlert(
      this,
      options,
    ));
  }

  /**
   * invoice.communication.triggered
   *
   * @remarks
   * Fired when an invoice communication (e.g. email notification) is triggered. Doc-only for parsing.
   */
  async postWebhookEventsInvoiceCommunicationTriggered(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoCommunicationWebhookPayload> {
    return unwrapAsync(
      webhookEventsPostWebhookEventsInvoiceCommunicationTriggered(
        this,
        options,
      ),
    );
  }

  /**
   * invoice.payment.overdue
   *
   * @remarks
   * Fired when an invoice payment is overdue past the due date. Doc-only for parsing.
   */
  async postWebhookEventsInvoicePaymentOverdue(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoInvoiceWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsInvoicePaymentOverdue(
      this,
      options,
    ));
  }

  /**
   * invoice.update
   *
   * @remarks
   * Fired when an invoice is updated. Doc-only for parsing.
   */
  async postWebhookEventsInvoiceUpdate(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoInvoiceWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsInvoiceUpdate(
      this,
      options,
    ));
  }

  /**
   * invoice.update.finalized
   *
   * @remarks
   * Fired when an invoice is finalized and locked for payment. Doc-only for parsing.
   */
  async postWebhookEventsInvoiceUpdateFinalized(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoInvoiceWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsInvoiceUpdateFinalized(
      this,
      options,
    ));
  }

  /**
   * invoice.update.payment
   *
   * @remarks
   * Fired when an invoice payment status changes. Doc-only for parsing.
   */
  async postWebhookEventsInvoiceUpdatePayment(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoInvoiceWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsInvoiceUpdatePayment(
      this,
      options,
    ));
  }

  /**
   * invoice.update.voided
   *
   * @remarks
   * Fired when an invoice is voided (e.g. order cancelled or duplicate). Doc-only for parsing.
   */
  async postWebhookEventsInvoiceUpdateVoided(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoInvoiceWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsInvoiceUpdateVoided(
      this,
      options,
    ));
  }

  /**
   * payment.created
   *
   * @remarks
   * Fired when a new payment is created. Doc-only for parsing.
   */
  async postWebhookEventsPaymentCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoPaymentWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsPaymentCreated(
      this,
      options,
    ));
  }

  /**
   * payment.failed
   *
   * @remarks
   * Fired when a payment fails. Doc-only for parsing.
   */
  async postWebhookEventsPaymentFailed(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoPaymentWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsPaymentFailed(
      this,
      options,
    ));
  }

  /**
   * payment.pending
   *
   * @remarks
   * Fired when a payment is pending processing. Doc-only for parsing.
   */
  async postWebhookEventsPaymentPending(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoPaymentWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsPaymentPending(
      this,
      options,
    ));
  }

  /**
   * payment.success
   *
   * @remarks
   * Fired when a payment succeeds. Doc-only for parsing.
   */
  async postWebhookEventsPaymentSuccess(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoPaymentWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsPaymentSuccess(
      this,
      options,
    ));
  }

  /**
   * payment.updated
   *
   * @remarks
   * Fired when a payment is updated. Doc-only for parsing.
   */
  async postWebhookEventsPaymentUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoPaymentWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsPaymentUpdated(
      this,
      options,
    ));
  }

  /**
   * subscription.activated
   *
   * @remarks
   * Fired when a draft subscription is activated. Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionActivated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionActivated(
      this,
      options,
    ));
  }

  /**
   * subscription.cancelled
   *
   * @remarks
   * Fired when a subscription is cancelled (immediately or end-of-period). Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionCancelled(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionCancelled(
      this,
      options,
    ));
  }

  /**
   * subscription.created
   *
   * @remarks
   * Fired when a new subscription is created. Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionCreated(
      this,
      options,
    ));
  }

  /**
   * subscription.draft.created
   *
   * @remarks
   * Fired when a new draft subscription is created (not yet activated). Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionDraftCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionDraftCreated(
      this,
      options,
    ));
  }

  /**
   * subscription.paused
   *
   * @remarks
   * Fired when a subscription is paused. Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionPaused(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionPaused(
      this,
      options,
    ));
  }

  /**
   * subscription.phase.created
   *
   * @remarks
   * Fired when a new subscription phase is created. Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionPhaseCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionPhaseWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionPhaseCreated(
      this,
      options,
    ));
  }

  /**
   * subscription.phase.deleted
   *
   * @remarks
   * Fired when a subscription phase is deleted. Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionPhaseDeleted(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionPhaseWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionPhaseDeleted(
      this,
      options,
    ));
  }

  /**
   * subscription.phase.updated
   *
   * @remarks
   * Fired when a subscription phase is updated. Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionPhaseUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionPhaseWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionPhaseUpdated(
      this,
      options,
    ));
  }

  /**
   * subscription.renewal.due
   *
   * @remarks
   * Fired when a subscription renewal is upcoming (cron-driven). Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionRenewalDue(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionRenewalDue(
      this,
      options,
    ));
  }

  /**
   * subscription.resumed
   *
   * @remarks
   * Fired when a paused subscription is resumed. Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionResumed(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionResumed(
      this,
      options,
    ));
  }

  /**
   * subscription.updated
   *
   * @remarks
   * Fired when a subscription is updated (e.g. quantity, billing anchor, or metadata changes). Doc-only for parsing.
   */
  async postWebhookEventsSubscriptionUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoSubscriptionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsSubscriptionUpdated(
      this,
      options,
    ));
  }

  /**
   * wallet.created
   *
   * @remarks
   * Fired when a new wallet is created. Doc-only for parsing.
   */
  async postWebhookEventsWalletCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoWalletWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsWalletCreated(
      this,
      options,
    ));
  }

  /**
   * wallet.credit_balance.dropped
   *
   * @remarks
   * Fired when a wallet's credit balance drops below an alert threshold. Doc-only for parsing.
   */
  async postWebhookEventsWalletCreditBalanceDropped(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoWalletWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsWalletCreditBalanceDropped(
      this,
      options,
    ));
  }

  /**
   * wallet.credit_balance.recovered
   *
   * @remarks
   * Fired when a wallet's credit balance recovers above an alert threshold. Doc-only for parsing.
   */
  async postWebhookEventsWalletCreditBalanceRecovered(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoWalletWebhookPayload> {
    return unwrapAsync(
      webhookEventsPostWebhookEventsWalletCreditBalanceRecovered(
        this,
        options,
      ),
    );
  }

  /**
   * wallet.ongoing_balance.dropped
   *
   * @remarks
   * Fired when a wallet's ongoing balance drops below an alert threshold. Doc-only for parsing.
   */
  async postWebhookEventsWalletOngoingBalanceDropped(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoWalletWebhookPayload> {
    return unwrapAsync(
      webhookEventsPostWebhookEventsWalletOngoingBalanceDropped(
        this,
        options,
      ),
    );
  }

  /**
   * wallet.ongoing_balance.recovered
   *
   * @remarks
   * Fired when a wallet's ongoing balance recovers above an alert threshold. Doc-only for parsing.
   */
  async postWebhookEventsWalletOngoingBalanceRecovered(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoWalletWebhookPayload> {
    return unwrapAsync(
      webhookEventsPostWebhookEventsWalletOngoingBalanceRecovered(
        this,
        options,
      ),
    );
  }

  /**
   * wallet.terminated
   *
   * @remarks
   * Fired when a wallet is terminated. Doc-only for parsing.
   */
  async postWebhookEventsWalletTerminated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoWalletWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsWalletTerminated(
      this,
      options,
    ));
  }

  /**
   * wallet.transaction.created
   *
   * @remarks
   * Fired when a new wallet transaction is created (top-up, deduction, etc.). Doc-only for parsing.
   */
  async postWebhookEventsWalletTransactionCreated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoTransactionWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsWalletTransactionCreated(
      this,
      options,
    ));
  }

  /**
   * wallet.updated
   *
   * @remarks
   * Fired when a wallet is updated. Doc-only for parsing.
   */
  async postWebhookEventsWalletUpdated(
    options?: RequestOptions,
  ): Promise<models.WebhookDtoWalletWebhookPayload> {
    return unwrapAsync(webhookEventsPostWebhookEventsWalletUpdated(
      this,
      options,
    ));
  }
}
